<?php
/**
 * Template Name: Warunki Sprzedaży B2B
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
/* child override: Certyfikat Licencyjny zamiast 'zwolnienia z OZZ', ujednolicone pakiety/ceny do CMLP, usuniete limity metrazu */
get_header();
?>
<div class="legal-page-wrapper">
<div class="legal-content">
    <h1><?php esc_html_e( 'Warunki Sprzedaży B2B', 'hrl-theme' ); ?></h1>
<p class="legal-date"><?php esc_html_e( 'Ostatnia aktualizacja: 12 lipca 2026 r.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '1. Definicje', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Niniejsze Warunki Sprzedaży B2B określają zasady świadczenia usług licencjonowania muzyki komercyjnej w ramach platformy HardbanRecords Lab Commercial Music Licensing Platform CMLP. Sprzedawcą jest przedsiębiorstwo HardbanRecords Lab, świadczące usługi w zakresie tworzenia, licencjonowania i dystrybucji oryginalnej muzyki komercyjnej. Klientem jest każde podmiot gospodarczy, osoba prawna lub jednostka organizacyjna nieposiadająca osobowości prawnej, której ustawa przyznała osobowość prawną, nabywająca licencję na publiczne odtwarzanie muzyki w oznaczonym lokalu lub sieci lokali w ramach działalności gospodarczej. Licencją jest dokument elektroniczny uprawniający do publicznego odtwarzania utworów muzycznych z katalogu HardbanRecords Lab w oznaczonym lokalu lub sieci lokali, na warunkach określonych w niniejszym dokumencie i w umowie licencyjnej. Lokal oznacza pojedyncze miejsce prowadzenia działalności gospodarczej, w którym odtwarzana jest muzyka z katalogu HRL, określone w zamówieniu. Siecią lokali jest zespół lokali należących do tego samego podmiotu gospodarczego, korzystających ze wspólnej licencji w ramach jednego z pakietów wielolokalizacyjnych (Business lub Premium). Streamingu jest automatyczne, ciągłe odtwarzanie utworów przez system CMLP bez konieczności ręcznej obsługi przez pracownika lokalu. Panelu B2B jest dedykowany interfejs internetowy dostępny pod adresem cmlp.hardbanrecordslab.online, służący do zarządzania licencją, tworzenia playlist, monitorowania odtworzeń, generowania raportów oraz rozliczeń. Umowa licencyjna jest umową zawartą między Sprzedawcą a Klientem regulującą warunki świadczenia usługi CMLP.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'W przypadku gdy zapisy niniejszych warunków sprzedaży stoją w sprzeczności z zapisami Regulaminu Świadczenia Usług dostępnego pod adresem /regulamin/, stosuje się przepisy Regulaminu, ponieważ Regulamin stanowi dokument nadrzędny regulujący relacje między stronami w szerszym zakresie. Warunki Sprzedaży B2B stanowią zaś szczegółowe regulamin handlowy dotyczące aspektów transakcyjnych i rozliczeniowych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '2. Ceny i płatności', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Ceny usług licencyjnych podane na platformie HardbanRecords Lab wyrażone są w złotych polskich PLN i zawierają pełną kwotę podatku VAT zgodnie z obowiązującymi przepisami o podatku od towarów i usług, chyba że wskazano wyraźnie cenę netto. HardbanRecords Lab oferuje następujące pakiety licencyjne. Każdy pakiet zapewnia dostęp do autorskiego katalogu HRL i nie ogranicza liczby dostępnych utworów; cena zależy wyłącznie od pakietu i liczby lokalizacji, nie od metrażu lokalu ani wielkości miejscowości. Pakiet Starter, dostępny za 69 zł miesięcznie, obejmuje jedną lokalizację, katalog w formacie MP3 320 kbps oraz standardowe wsparcie techniczne. Pakiet Business, dostępny za 159 zł miesięcznie, obejmuje do pięciu lokalizacji, harmonogramy playlist, konta pracowników, priorytetowe wsparcie oraz raporty odtworzeń. Pakiet Premium, dostępny za 499 zł miesięcznie, obejmuje do piętnastu lokalizacji, katalog w jakości FLAC, odtwarzacz white-label z własną subdomeną oraz rozbudowaną analitykę odtworzeń. Pakiet Event, dostępny za 600 zł jednorazowo, obejmuje dostęp do pełnej biblioteki przez 24 godziny na potrzeby konkretnego wydarzenia. Pakiet Custom, wyceniany indywidualnie, obejmuje nieograniczoną liczbę lokalizacji, dostęp do API, dedykowanego opiekuna konta, ustalenia dotyczące poziomu dostępności usługi (SLA) oraz możliwość integracji z systemami zewnętrznymi. Aktualne ceny i szczegóły pakietów prezentowane są na stronie CMLP. Płatności realizowane są wyłącznie za pośrednictwem zaufanych certyfikowanych operatorów płatności elektronicznych. Faktury VAT wystawiane są automatycznie w formie elektronicznej na adres e-mail wskazany w Panelu B2B niezwłocznie po zaksięgowaniu płatności. W przypadku potrzeby wystawienia faktury w formie papierowej, klient zobowiązany jest do złożenia osobnego żądania z opłatą dodatkową zgodną z aktują cennikiem usług dodatkowych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '3. Okres obowiązywania licencji', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Wszystkie licencje udzielane są na okres 12 miesięcy kalendarzowych, licząc od daty aktywacji płatności w systemie operatora płatności. Okres obowiązywania licencji jest oznaczony w potwierdzeniu płatności, fakturze oraz w Panelu B2B w zakładce Ustawienia licencja. Licencja odnawia się automatycznie na kolejne okresy 12-miesięczne, chyba że Klient wyraźnie wypowie umowę zgodnie z zapisami niniejszych warunków sprzedaży. Klient może wybrać nowy pakiet licencyjny, zmiana wchodzi w życie od początku następnego okresu rozliczeniowego. W przypadku zmiany planu na mniej kosztowny, różnica kwot jest proporcjonalnie zwracana klientowi w formie kredytu na kolejny okres rozliczeniowy lub w formie zwrotu na konto bankowe w ciągu 14 dni roboczych. Administrator zastrzega sobie prawo do zmiany cen pakietów licencyjnych w dowolnym momencie, o czym poinformuje Klientów z 30-dniowym wyprzedzeniem przed rozpoczęciem nowego okresu rozliczeniowego. W Takim przypadku Klient ma prawo do wypowiedzenia umowy bez ponoszenia dodatkowych kosztów. W przypadku opóźnienia płatności o więcej niż 7 dni od terminu wymagalności, dostęp do katalogu utworów może zostać tymczasowo zablokowany przez automatyczny system do momentu uregulowania zaległej kwoty. Klient otrzymuje automatyczne powiadomienia o zbliżającym się terminie płatności oraz opóźnieniu płatności na adres e-mail powiązany z kontem.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '4. Zwroty i odstąpienie od umowy', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Klient będący konsumentem ma zgodnie z ustawą z dnia 30 maja 2014 r. o prawach konsumentów prawo odstąpić od umowy sprzedaży w terminie 14 dni kalendarzowych od dnia zawarcia umowy bez podania przyczyny i bez ponoszenia kosztów. Oświadczenie o odstąpieniu od umowy powinno zostać wysłane na adres e-mail contact@hardbanrecordslab.online lub na adres siedziby Sprzedawcy. Jednocześnie Klient wyraźnie zgadza się na rozpoczęcie świadczenia usługi platformy streamingowej natychmiast po zaksięgowaniu płatności, zgodnie z art. 38 ust. 1 ustawy o prawach konsumentów. Rozpoczęcie korzystania z platformy CMLP oznacza wyrażenie zgody na trwałe wykonanie umowy i utratę prawa do odstąpienia od umowy w okresie 14-dniowym. Klient B2B korzystający z usług w ramach działalności gospodarczej nie ma prawa odstąpienia od umowy w okresie 14-dniowym. W przypadku klientów biznesowych korzystających z usług w formie subskrypcji, umowa wiąże się z automatuwnym odnawianiem na kolejne okresy rozliczeniowe zgodnie z zapisami niniejszych warunków sprzedaży. W przypadku udzielenia rabatu lub specjalnej oferty promocyjnej, Klient zobowiązany jest do spełnienia warunków promocji, w tym do pozostania w ramach określonego pakietu przez minimalny okres 3 miesięcy.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '5. Certyfikat Licencyjny', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Każdy Klient posiadający aktywną licencję otrzymuje automatycznie wygenerowany Certyfikat Licencyjny, dostępny do pobrania z Panelu B2B oraz przesyłany w formie pliku PDF na adres e-mail Klienta w dniu aktywacji licencji. Certyfikat zawiera: identyfikator licencji unikalny w systemie HRL, nazwę Klienta lub lokalu wskazaną przy zamówieniu, zakres terytorialny licencji, datę rozpoczęcia i zakończenia jej obowiązywania, listę objętych lokalizacji oraz kod QR umożliwiający weryfikację autentyczności i ważności dokumentu. Certyfikat potwierdza, że wskazana lokalizacja korzysta z aktywnej licencji na katalog HardbanRecords Lab udzielonej bezpośrednio przez administratora. Klient może w dowolnym momencie pobrać kopię certyfikatu z Panelu B2B lub zażądać ponownego przesłania go na adres kontaktowy. Certyfikat nie przesądza o zakresie ewentualnych uprawnień lub roszczeń podmiotów trzecich i nie zastępuje samodzielnej oceny prawnej sytuacji Klienta.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '6. Rozwiązanie umowy', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Umowa licencyjna może zostać rozwiązana przez Klienta w dowolnym momencie z 30-dniowym okresem wypowiedzenia, bez podania przyczyny i bez ponoszenia dodatkowych kosztów. Rozwiązanie umowy następuje na koniec bieżącego okresu rozliczeniowego. Klient może wypowiedzieć umowę wyłącznie przez Panel B2B w zakładce Ustawienia licencja lub wysyłając wiadomość e-mail na adres contact@hardbanrecordslab.online z wyraźnym wskazaniem chęci wypowiedzenia umowy. Administrator zobowiązuje się do potwierdzenia otrzymania wypowiedzenia w ciągu 3 dni roboczych i poinformowania Klienta o dniu końca obowiązywania umowy. Administrator ma prawo do natychmiastowego rozwiązania umowy w przypadku: naruszenia warunków licencji przez Klienta, wykorzystania utworów w sposób niezgodny z przeznaczeniem lub wykraczający poza zakres licencji, podejmowania prób dekompilacji oprogramowania platformy, nadużywania zasobów systemowych, ataków na infrastrukturę administratora, opóźnienia płatności o więcej niż 14 dni, lub działania siły wyższej utrudniającego świadczenie usług przez okres przekraczający 30 dni. Po rozwiązaniu umowy, Klient zobowiązany jest do natychmiastowego zaprzestania odtwarzania utworów z katalogu HRL, usunięcia wszystkich skopiowanych plików audio z urządzeń oraz powstrzymania się od dalszego korzystania z Panelu B2B i API. W przypadku rozwiązania umowy w związku z naruszeniem warunków przez Klienta, administrator zastrzega sobie prawo do utrzymania opłaty za bieżący okres rozliczeniowy.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '7. Dane kontaktowe i postanowienia końcowe', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W sprawach dotyczących sprzedaży, rozliczeń, konsultacji technicznych i reklamacji Klient może kontaktować się z HardbanRecords Lab pod następującymi danymi kontaktowymi: adres e-mail contact@hardbanrecordslab.online przeznaczony do spraw ogólnych i obsługi klienta, numer telefonu +48 726 651 384 dostępny w godzinach pracy 8-16 w dni robocze, oraz adresem siedziby HardbanRecords Lab, Polska, do korespondencji pisemnej. Administrator udziela odpowiedzi na zapytania i reklamacje w ciągu 14 dni roboczych od dnia otrzymania zapytania, a w przypadku spraw priorytetowych klientów pakietów Premium i Custom w ciągu 8 godzin roboczych. W przypadku niezakończonych sporów dotyczących wykonania umowy, strony zobowiązują się do rozstrzygnięcia sporu na drodze mediacji z wybranym przez strony mediatorami przed skierowaniem sprawy do sądu. Wszelkie reklamacje powinny być wniesione na piśmie w formie elektronicznej lub listowane, z opisem przyczyny reklamacji oraz proponowanym sposobem rozwiązania problemu. Administrator zastrzega sobie prawo do modyfikacji niniejszych warunków sprzedaży w dowolnym momencie z przyczyn uzasadnionych, o czym poinformuje Klientów z 14-dniowym wyprzedzeniem. Klienci, którzy nie zgadzają się z nowymi warunkami, mają prawo do wypowiedzenia umowy bez dodatkowych kosztów do momentu wejścia zmian w życie.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'W sprawach nieuregulowanych przez niniejsze Warunki Sprzedaży B2B zastosowanie mają przepisy prawa polskiego, w szczególności Kodeksu Cywilnego, ustawy o świadczeniu usług drogą elektroniczną, ustawy o prawach konsumentów oraz inne obowiązujące akty prawne. Klient ma prawo do skorzystania z platformy rozstrzygania sporów online ODR dostępnej pod adresem https://ec.europa.eu/consumers/odr, zgodnie z rozporządzeniem UE nr 524/2013. Wszelkie spory między Sprzedawcą a Klientem rozstrzygane będą przez sąd powszechny właściwy dla siedziby Sprzedawcy, chyba że przepisy obowiązującego prawa wymagają innego sądu właściwego.', 'hrl-theme' ); ?></p>
</div><!-- .legal-content -->
</div><!-- .legal-page-wrapper -->
<?php get_footer(); ?>
