<?php
/**
 * Template Name: Contact
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<section class="hero" style="min-height:40vh;">
    <div class="hero-content">
        <p class="hero-eyebrow"><?php esc_html_e( 'Kontakt', 'hrl-theme' ); ?></p>
        <h1><?php esc_html_e( 'Skontaktuj się z HardbanRecords Lab', 'hrl-theme' ); ?></h1>
        <p class="hero-desc"><?php esc_html_e( 'Masz pytania dotyczące licencjonowania muzyki komercyjnej B2B, współpracy biznesowej, zamówień indywidualnych utworów na zamówienie, integracji API z systemami POS i aplikacjami mobilnymi, problemów technicznych z platformą CMLP, White-Label Player, trybu offline lub reklamacji dotyczących świadczonych usług? Wypełnij formularz kontaktowy lub skorzystaj z innych metod kontaktu wymienionych poniżej. Nasz zespół obsługi klienta składa się z doświadczonych specjalistów od branży muzycznej i licencjonowania, którzy udzielą Ci szczegółowej odpowiedzi w ciągu 24 godzin roboczych w dni robocze od poniedziałku do piątku w godzinach 8-16 czasu polskiego standardowego. Dla klientów Enterprise, którzy mają aktywną umowę SLA, czas odpowiedzi na zapytania priorytetowe wynosi do 8 godzin roboczych, a w przypadku incydentów krytycznych do 1 godziny roboczej. W sprawach pilnych prosimy o oznaczenie tematu jako Pilne w formularzu kontaktowym.', 'hrl-theme' ); ?></p>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="product-grid" style="max-width:1100px;margin:0 auto;">
            <div style="grid-column:span 1;">
                <h2 style="margin-bottom:24px;"><?php esc_html_e( 'Formularz kontaktowy', 'hrl-theme' ); ?></h2>
                <?php esc_html_e( 'Wypełnij poniższy formularz, aby skontaktować się z zespołem HardbanRecords Lab. Wszystkie pola oznaczone gwiazdką są wymagane. Postaraj się podać jak najwięcej szczegółów, abyśmy mogli Ci pomóc w sposób najskuteczniejszy. W przypadku zapytań o konfigurację techniczną, prosimy o podanie informacji dotyczących systemu operacyjnego urządzeń, rozmiaru lokalu oraz wybranego pakietu licencyjnego.', 'hrl-theme' ); ?>
                <p style="margin-top:32px;padding:28px;background:rgba(255,255,255,0.04);border-left:4px solid var(--accent-primary);border-radius:0 8px 8px 0;"><?php esc_html_e( 'HardbanRecords Lab jest otwarta na współpracę z przedsiębiorcami, właścicielami lokali gastronomicznych, sieciami handlowymi, hotelarstwem, organizatorami wydarzeń oraz każdym podmiotem zainteresowanym legalnym licencjonowaniem muzyki komercyjnej. Nasz zespół oferuje pełne wsparcie od momentu zapoznania się z ofertą, przez wybór odpowiedniego pakietu licencyjnego, onboarding i konfigurację platformy w lokalu, aż po stałą obsługę w trakcie trwania umowy. Jesteśmy do dyspozycji w godzinach 8-16 czasu polskiego w dni robocze od poniedziałku do piątku. W sprawach priorytetowych klientów Enterprise, opiekun konta dostępny jest również po godzinach pracy po wcześniejszym umówieniu. Odpowiadamy na wszystkie zapytania w ciągu 24 godzin roboczych, a sprawy priorytetowe w ciągu 8 godzin roboczych. Jeśli potrzebujesz pomocy z konfiguracją odtwarzacza, wyborem playlisty dla swojego lokalu lub masz pytania dotyczące integracji API, napisz do nas. Nasz zespół składa się z doświadczonych specjalistów od branży muzycznej i technologii, którzy pomogą Ci w każdej kwestii.', 'hrl-theme' ); ?></p>
<form class="contact-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="margin-top:20px;">
                    <input type="hidden" name="action" value="hrl_contact_form">
                    <?php wp_nonce_field( 'hrl_contact_action', 'hrl_contact_nonce' ); ?>
                    <div class="form-group"><label class="form-label" for="contact_name"><?php esc_html_e( 'Imię i Nazwisko', 'hrl-theme' ); ?></label><input type="text" id="contact_name" name="contact_name" class="form-input" required placeholder="np. Jan Kowalski"></div>
                    <div class="form-group"><label class="form-label" for="contact_email"><?php esc_html_e( 'Adres e-mail', 'hrl-theme' ); ?></label><input type="email" id="contact_email" name="contact_email" class="form-input" required placeholder="np. jan@firma.pl"></div>
                    <div class="form-group"><label class="form-label" for="contact_company"><?php esc_html_e( 'Nazwa firmy', 'hrl-theme' ); ?></label><input type="text" id="contact_company" name="contact_company" class="form-input" placeholder="np. Twoja Firma Sp. z o.o."></div>
                    <div class="form-group"><label class="form-label" for="contact_subject"><?php esc_html_e( 'Temat', 'hrl-theme' ); ?></label><input type="text" id="contact_subject" name="contact_subject" class="form-input" required placeholder="np. Zapytanie o pakiet Business, licencja dla 3 lokali"></div>
                    <div class="form-group"><label class="form-label" for="contact_message"><?php esc_html_e( 'Wiadomość', 'hrl-theme' ); ?></label><textarea id="contact_message" name="contact_message" class="form-textarea" required rows="8" placeholder="Opisz swoje pytanie lub zapytanie w jak najwięcej szczegółów. W przypadku problemów technicznych prosimy o podanie: nazwy urządzenia, systemu operacyjnego, numeru wersji aplikacji CMLP Player, opisu problemu oraz kroków, które prowadzą do wystąpienia błędu. Im więcej szczegółów podasz, tym szybciej nasz zespól będzie mógł Ci pomóc."></textarea></div>
                    <div class="form-group" style="font-size:0.85rem;color:var(--text-secondary);margin-top:16px;"><?php esc_html_e( 'Wysyłając formularz, wyrażasz zgodę na przetwarzanie danych osobowych zgodnie z naszą Polityką Prywatności dostępną pod adresem /privacy/. Dane nie są przekazywane podmiotom trzecim bez Twojej wyraźnej zgody, z wyjątkiem podmiotów świadczących usługi na rzecz administratora zgodnie z umowami powierzenia przetwarzania. Masz prawo do dostępu do swoich danych, ich sprostowania lub usunięcia w dowolnym momencie, kontaktując się z nami pod adresem contact@hardbanrecordslab.online.', 'hrl-theme' ); ?></div>
                    <button type="submit" class="btn btn-primary" style="width:100%;"><?php esc_html_e( 'Wyślij wiadomość →', 'hrl-theme' ); ?></button>
                </form>
                <?php if ( isset( $_GET['contact'] ) && 'success' === $_GET['contact'] ) : ?>
                    <p style="color:var(--market-up);font-size:0.95rem;margin-top:20px;font-weight:600;">✓ <?php esc_html_e( 'Dziękujemy! Wiadomość wysłana pomyślnie. Odpowiemy w ciągu 24 godzin roboczych. Sprawdź swoją skrzynkę e-mail w tym czasie, a także folder spamowy, jeśli nie znajdziesz wiadomości w skrzynce głównej.', 'hrl-theme' ); ?></p>
                <?php elseif ( isset( $_GET['contact'] ) && 'error' === $_GET['contact'] ) : ?>
                    <p style="color:var(--market-down);font-size:0.95rem;margin-top:20px;font-weight:600;">✕ <?php esc_html_e( 'Wystąpił błąd podczas wysyłania wiadomości. Spróbuj ponownie lub skontaktuj się z nami bezpośrednio pod adresem e-mail contact@hardbanrecordslab.online lub telefonicznie pod numerem +48 726 651 384, aby uzyskać natychmiastową pomoc.', 'hrl-theme' ); ?></p>
                <?php endif; ?>
            </div>
            <div>
                <div class="product-card" style="margin-bottom:20px;"><div class="product-card-icon">📧</div><h3><?php esc_html_e( 'Email', 'hrl-theme' ); ?></h3><p><a href="mailto:contact@hardbanrecordslab.online">contact@hardbanrecordslab.online</a></p><p style="font-size:0.85rem;color:var(--text-secondary);margin-top:8px;"><?php esc_html_e( 'Adres e-mail do spraw ogólnych i obsługi klienta. Możesz wysyłać zapytania dotyczące licencjonowania, współpracy biznesowej, zamówień indywidualnych, integracji API, White-Label Player, raportów technicznych, reklamacji i wszystkich innych spraw związanych z działalnością HardbanRecords Lab.', 'hrl-theme' ); ?></p></div>
                <div class="product-card" style="margin-bottom:20px;"><div class="product-card-icon">📞</div><h3><?php esc_html_e( 'Telefon', 'hrl-theme' ); ?></h3><p><a href="tel:+48726651384">+48 726 651 384</a></p><p style="font-size:0.85rem;color:var(--text-secondary);margin-top:8px;"><?php esc_html_e( 'Dostępny po wcześniejszym umówieniu w godzinach 8-16 czasu polskiego w dni robocze. Nasz zespół obsługi klienta mówi po polsku i angielsku. W przypadku spraw priorytetowych klientów Enterprise, możliwość kontaktu po standardowych godzinach pracy po wcześniejszym uzgodnieniu z opiekunem konta. Prosimy o wcześniejsze wysłanie e-maila z zapytaniem o rozmowę telefoniczną, aby opiekun mógł przygotować się do spotkania, w tym sprawdzić historię współpracy i dane konfiguracyjne.', 'hrl-theme' ); ?></p></div>
                <div class="product-card" style="margin-bottom:20px;"><div class="product-card-icon">⏱️</div><h3><?php esc_html_e( 'Czas Odpowiedzi', 'hrl-theme' ); ?></h3><p><?php esc_html_e( 'Standardowy czas odpowiedzi wynosi do 24 godzin roboczych na zapytania wysłane przez formularz kontaktowy lub e-mail. Klienci z pakietu Enterprise mają przypisanego opiekuna konta z priorytetowym dostępem i czasem odpowiedzi do 8 godzin roboczych. Incydenty krytyczne blokujące działanie platformy w lokalu rozpatrywane są w pierwszej kolejności, czas odpowiedzi wynosi do 1 godziny roboczej zgodnie z umową SLA.', 'hrl-theme' ); ?></p></div>
                <div class="product-card" style="margin-bottom:20px;"><div class="product-card-icon">💼</div><h3><?php esc_html_e( 'Kariera i Spółka', 'hrl-theme' ); ?></h3><p><a href="<?php echo esc_url( home_url( '/kariera' ) ); ?>"><?php esc_html_e( 'Zobacz oferty pracy', 'hrl-theme' ); ?></a></p><p style="font-size:0.85rem;color:var(--text-secondary);margin-top:8px;"><?php esc_html_e( 'HardbanRecords Lab stale poszukuje talentów w obszarze kompozycji muzyki, inżynierii audio, rozwoju oprogramowania, obsługi klienta biznesowego, marketingu i sprzedaży B2B. Zapraszamy do zapoznania się z aktualnymi ofertami pracy na stronie /kariera/. Świadczymy elastyczne godziny pracy, możliwość pracy zdalnej, budżet szkoleniowy oraz rozwojowy, prywatne ubezpieczenie medyczne oraz karta sportowa. W sprawach współpracy biznesowej, dystrybucji, programów partnerskich i re sellerskich prosimy o kontakt na adres partnerships@hardbanrecordslab.online.', 'hrl-theme' ); ?></p></div>
            </div>
        </div>
    </div>
</section>
<?php get_footer(); ?>