<?php
/**
 * Template Name: FAQ
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<section class="hero" style="min-height:30vh;">
    <div class="hero-content">
        <p class="hero-eyebrow"><?php esc_html_e( 'Pytania i Odpowiedzi', 'hrl-theme' ); ?></p>
        <h1><?php esc_html_e( 'Najczęściej Zadawane Pytania', 'hrl-theme' ); ?></h1>
        <p class="hero-desc"><?php esc_html_e( 'Znajdź odpowiedzi na pytania dotyczące licencjonowania muzyki komercyjnej, platformy CMLP, subskrypcji B2B, obsługi technicznej, polityki bezpieczeństwa oraz warunków współpracy z HardbanRecords Lab. Jeśli nie znajdziesz odpowiedzi na swoje pytanie w poniższym zakres, skontaktuj się z nami bezpośrednio przez formularz kontaktowy, e-mail lub telefon.', 'hrl-theme' ); ?></p>
    </div>
</section>

<section class="section">
    <div class="container">
        <p style="margin-bottom:30px;padding:24px;background:rgba(255,255,255,0.04);border-left:4px solid var(--accent-primary);border-radius:0 8px 8px 0;"><?php esc_html_e( 'Poniższe pytania i odpowiedzi zostały przygotowane na podstawie najczęstszych zapytań otrzymywanych przez dział obsługi klienta HardbanRecords Lab. Zakres pytania obejmuje kategorie: płatności i rozliczenia, licencjonowanie i umowy, integracje techniczne, obsługa klienta, bezpieczeństwo danych oraz funkcjonalności platformy. Jeśli Twoje pytanie nie zostało poruszone poniżej, skontaktuj się z nami bezpośrednio.', 'hrl-theme' ); ?></p>
<div class="faq-list">
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Jakie są metody płatności?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Akceptujemy płatności kartą kredytową debitową Visa Mastercard American Express przez platformę Stripe Payments Europe Limited, bezpieczne płatności PayPal dla klientów międzynarodowych oraz przelewem online BLIK lub tradycyjnym przez PayU S.A. Dla klientów korporacyjnych z regularnymi transakcjami i osobistymi relacjami biznesowymi oferujemy również płatności na podstawie faktury pro forma z 14-dniowym terminem płatności oraz płatności prolongatowe dla klientów Enterprise. Wszystkie płatności są przetwarzane na bezpiecznych serwerach operatorów płatności spełniających wymagania PCI DSS. HardbanRecords Lab nie przechowuje danych kart płatniczych na własnych serwerach. Płatności są rozliczane w czasie rzeczywistym, a faktura VAT wystawiana automatycznie po zaksięgowaniu płatności w formie elektronicznej na adres e-mail wskazany w Panelu B2B.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Jak długo trwa ważność licencji?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Licencja B2B udzielana jest na okres 12 miesięcy kalendarzowych od daty aktywacji płatności w systemie operatora płatności. Okres obowiązywania licencji jest oznaczony w potwierdzeniu płatności, fakturze oraz w Panelu B2B w zakładce Ustawienia licencja. Licencja odnawia się automatycznie na kolejne okresy 12-miesięczne, chyba że Klient wyraźnie wypowie umowę z 30-dniowym wyprzedzeniem przed końcem okresu rozliczeniowego. Certyfikat Zwolnienia z OZZ generowany jest automatycznie przy każdej aktywacji subskrypcji i dostępny do pobrania przez cały okres świadczenia usług. W przypadku przerwania płatności o więcej niż 7 dni od terminu wymagalności, dostęp do katalogu utworów może zostać tymczasowo zablokowany przez automatyczny system do momentu uregulowania zaległej kwoty. Klient otrzymuje automatyczne powiadomienia o zbliżającym się terminie płatności oraz o ewentualnym opóźnieniu na adres e-mail powiązany z kontem.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Czy naprawdę nie muszę płacić ZAiKS, STOART, ZPAV lub SAWP?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Tak. Wszystkie utwory w katalogu HardbanRecords Lab są w 100% autorskie i stworzone wyłącznie przez zespół compositorów zatrudnionych lub współpracujących z HardbanRecords Lab na podstawie umowy z przeniesieniem pełnych praw autorskich na administratora. Ponieważ utwory nie podlegają jurysdykcji organizacji zbiorowego zarządzania prawami autorskimi, Klient nie ma obowiązku płacenia dodatkowych opłat tantiemalnych za publiczne odtwarzanie muzyki w ramach licencji CMLP. Otrzymujesz Certyfikat Zwolnienia z Opłat Zbiorowych wygenerowany automatycznie przez system z unikalnym kodem QR, który stanowi dowód legalnego źródła muzyki podczas ewentualnej kontroli organów nadzorczych lub przedstawicieli organizacji zbiorowych. Certyfikat może być dowolnie wielokrotnie pobierany z Panelu B2B.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Czy mogę zintegrować odtwarzacz przez API z moim systemem POS?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Tak. Dla klientów pakietu Enterprise oferujemy pełny dostęp do interfejsu API REST w wersji 3 umożliwiającego integrację odtwarzacza CMLP z dowolnymi systemami POS, aplikacjami mobilnymi, panelami zarządzania, systemami automatyki budynku oraz innymi narzędziami biznesowymi Klienta. API obsługuje wszystkie operacje CRUD, zapisywanie playlisty, zarządzanie urządzeniami odtwarzającymi oraz pobieranie analityki odtworzeń w formacie JSON. Dokumentacja API dostępna jest pod adresem docs.cmlp.hardbanrecordslab.online po zalogowaniu się do Panelu B2B. Dostęp do API wymaga tokenu autoryzacyjnego JWT, który można wygenerować w Panelu B2B w zakładce Ustawienia integracje. Domyślny limit dla planów Enterprise wynosi 1000 zapytań na godzinę na konto.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Czym jest White-Label Player i dla kogo jest przeznaczony?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'White-Label Player to dedykowana wersja odtwarzacza muzycznego CMLP dostosowana do brandingu Klienta, umożliwiająca odtwarzanie muzyki pod własną subdomeną np. muzyka.twojafirma.pl z własnym logo, nazwą handlową i paletą kolorów dostosowaną do identyfikacji wizualnej marki. Usługa dostępna jest dla klientów pakietów Premium i Enterprise. Klient otrzymuje pełną kontrolę nad interfejsem użytkownika, może dodawać własne playlisty, ustawiać harmonogramy odtwarzania według pory dnia oraz zarządzać wieloma urządzeniami odtwarzającymi z jednego Panelu B2B. Klient nie ma prawa do modyfikacji rdzenia odtwarzacza, dekompilacji ani wykorzystania go do celów konkurencyjnych. Konfiguracja subdomeny, certyfikatu SSL oraz dostosowanie DNS pozostaje w gestii Klienta i może wymagać współpracy z administratorem systemu DNS firmy. HardbanRecords Lab zastrzega sobie prawo do wycofania subdomeny w przypadku naruszenia warunków licencji.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Jak skontaktować się z działem obsługi klienta?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Skontaktować się z nami można na kilka sposobów: pisemnie przez formularz kontaktowy dostępny na stronie hardbanrecordslab.online /contact/, wysyłając wiadomość e-mail na adres contact@hardbanrecordslab.online, dzwoniąc pod numer +48 726 651 384 dostępny w godzinach 8-16 czasu polskiego standardowego w dni robocze od poniedziałku do piątku, lub wysyłając zapytanie przez ticket system dostępny w Panelu B2B w zakładce Wsparcie. Czas odpowiedzi na zapytania wysłane przez formularz lub e-mail wynosi do 24 godzin roboczych. Klienci z pakietu Enterprise mają przypisanego dedykowanego opiekuna konta z priorytetowym dostępem, czas odpowiedzi na zapytania priorytetowe wynosi do 8 godzin roboczych. W przypadku pilnych spraw technicznych blokujących działanie platformy lub muzyki w lokalu, prosimy o wskazanie tematu jako Pilne w formularzu kontaktowym aby priorytetyzować Twoje zapytanie.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Czy oferujecie muzykę dla konkretnych branż?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Tak. Nasz katalog obejmuje utwory specjalnie przygotowane lub dopasowane do profilu akustycznego różnych branż. Oferujemy playlisty i sugestie dla: hoteli i apartamentów kommercyjnych, restauracji i lokali gastronomicznych w tym funkcjonujących przy drogach ekspresowych i autostradach, kawiarni i cukierni, siłowni i klubów fitness centrów wellness i spa, galerii sztuki i muzeów, korporacji i przestrzeni biurowych, eventów firmowych i konferencji, sklepów i galerii handlowych, szpitali i przychodni zdrowotnych, szkół i uczelni oraz domestycznych przestrzeni coworkingowych. Każda playlista dostosowana jest do profilu lokalu, rozmiaru przestrzeni, charakteru ruchu, godziny dnia oraz preferencji docelowej grupy odbiorców. W przypadku wymagań specyficznych, możemy przygotować spersonalizowaną playlistę na zamówienie w ramach usługi Muzyczna Kreacja Słów, gdzie kompozytorzy tworzą utwory dostosowane do marki i charakteru lokalu.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Jak uruchomić platformę w moim lokalu?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Proces uruchomienia platformy w lokalu odbywa się w kilku prostych krokach. Po zakupie licencji i zaksięgowaniu płatności, Klient otrzymuje automatycznie powiadomienie e-mail z linkiem do Panelu B2B oraz danymi dostępowymi. W Panelu B2B Klient konfiguruje konto, dodaje lokalizacje, wybiera playlistę startową z katalogu oraz generuje kod QR lub link django startowy do uruchomienia odtwarzacza. Następnie pobiera aplikację CMLP Player dostępną na urządzeniach z systemem Android lub iOS, lub uruchamia odtwarzacz w dowolnej przeglądarce internetowej na tablecie, laptopie lub komputerze stacjonarnym. Logując się za pomocą danych dostarczonych przez administratora, Klient wybiera playlistę, ustawia poziom głośności i rozpocznas odtwarzanie muzyki. W przypadku pakietów Enterprise, zespół HRL oferuje pomoc przy konfiguracji za pomocą sesji onboardingowej zdalnej dostępnej w języku polskim i angielskim, zawsze w ciągu 3 dni roboczych od aktywacji licencji. Klient otrzymuje również szkolenie z obsługi Panelu B2B oraz wskazówki dotyczące optymalizacji odtwarzania w lokalu pod kątem jakości dźwięku i komfortu gości.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Czy mogę zmienić pakiet licencyjny?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Tak. Klient może zmienić pakiet licencyjny w dowolnym momencie na wyższy lub niższy pakiet. Zmiana na pakiet wyższy wchodzi w życie natychmiast po zaksięgowaniu opłaty różnicy, z proporcjonalnym rozliczeniem różnicy kwoty za pozostały okres rozliczeniowy. Zmiana na pakiet niższy wchodzi w życie od początku następnego okresu rozliczeniowego, chyba że klient wyraźnie zażąda wcześniejszej zmiany, w przypadku czego administrator rozliczy różnicę proporcjonalnie i zwróci klientowi odpowiednią kwotę w ciągu 14 dni roboczych. W przypadku zwiększenia liczby lokalizacji lub rozmiaru katalogu, rozliczenie następuje zgodnie z aktualnym cennikiem. Administrator nie pobiera dodatkowych opłat administracyjnych za zmianę pakietu. Wszelkie zmiany pakietu muszą być potwierdzone przez administratora w Systemie B2B w ciągu 3 dni roboczych.', 'hrl-theme' ); ?></p></div>
            </div>
            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Jakie dane są zbierane przez platformę i czy są bezpieczne?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'HardbanRecords Lab zbiera wyłącznie dane niezbędne do świadczenia usług zgodnie z zasadą minimalizacji danych: dane identyfikacyjne firmy, dane kontaktowe osoby upoważnionej, dane do faktur, dane logowania do Panelu B2B, dane dotyczące odtworzeń, playlist, aktywności w platformie, dane płatności przetwarzane wyłącznie przez zewnętrznych operatorów płatności. Dane te są przetwarzane zgodnie z RODO i przechowywane przez okres nie dłuższy, niż jest to niezbędne do celów, dla których są przetwarzane. Pełna informacja dotycząca przetwarzania danych osobowych dostępna jest w Polityce Prywatności dostępnej pod adresem /privacy/. HardbanRecords Lab nie sprzedaje ani nie udostępnia danych osobowych klientów podmiotom trzecim bez wyraźnej zgody, z wyjątkiem podmiotów świadczących usługi na rzecz administratora zgodnie z umowami powierzenia przetwarzania. Dane są zabezpieczane za pomocą szyfrowania TLS 1,3, hashowania bcrypt haseł oraz regularnych kopii zapasowych. W przypadku stwierdzenia naruszenia bezpieczeństwa danych, administrator niezwłocznie powiadomi użytkowników i organ nadzorczy.', 'hrl-theme' ); ?></p></div>
            </div>
        <p style="margin-top:20px;padding:24px;background:rgba(255,255,255,0.04);border-left:4px solid var(--accent-primary);border-radius:0 8px 8px 0;"><?php esc_html_e( 'Jeśli nadal nie znalazłeś odpowiedzi na swoje pytanie dotyczące procesu rejestracji, wymagań systemowych, synchronizacji playlisty między urządzeniami, trybu offline czy możliwości personalizacji playlisty dla swojego lokalu, skontaktuj się z zespołem obsługi klienta HardbanRecords Lab. Jesteśmy dostępni pod adresem contact@hardbanrecordslab.online oraz numerem telefonu +48 726 651 384. Staramy się odpowiadać na wszystkie zapytania w ciągu 24 godzin roboczych, a sprawy priorytetowe dla klientów Enterprise w ciągu 8 godzin roboczych. Nasz zespół obsługi klienta składa się z doświadczonych specjalistów od obsługi klienta biznesowego, którzy znają specyfikę branży muzycznej i licencjonowania na Detailed poziomie. Jesteśmy do dyspozycji w godzinach 8-16 czasu polskiego w dni robocze od poniedziałku do piątku.', 'hrl-theme' ); ?></p>            <div class="faq-item">
                <button class="faq-question"><?php esc_html_e( 'Czy platforma działa offline?', 'hrl-theme' ); ?></button>
                <div class="faq-answer"><p><?php esc_html_e( 'Dla klientów z pakietu Premium i Enterprise oferujemy tryb offline, który umożliwia pobranie playlisty na urządzenia mobilne i odtwarzanie muzyki bez stałego połączenia z internetem. Utwory przechowywane są w zaszyfrowanej formie na urządzeniu, co zapobiega nieautoryzowanemu kopiowaniu. Tryb offline jest szczególnie przydatny w lokacjach z słabym zasięgiem internetowym lub podczas awarii infrastruktury sieciowej. Po odzyskaniu połączenia, aplikacja automatycznie synchronizuje historię odtworzeń i aktualizuje playlisty. Urządzenia muszą być zarejestrowane w Panelu B2B, a liczba równoległych urządzeń offline jest ograniczona do 5 na pakiet Premium i 20 na pakiet Enterprise. Wszystkie urządzenia offline są monitorowane pod kątem zgodności z zakresem licencji.', 'hrl-theme' ); ?></p></div>
            </div>

</div>
    </div>
</section>
<?php get_footer(); ?>