<?php
/**
 * Template Name: Regulamin Licencji
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<div class="legal-page-wrapper">
<div class="legal-content">
    <h1><?php esc_html_e( 'Regulamin Licencji', 'hrl-theme' ); ?></h1>
    <p class="legal-date"><?php esc_html_e( 'Ostatnia aktualizacja: 12 lipca 2026 r.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '1. Definicje i interpretacja', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Niniejszy Regulamin Licencji określa zakres, warunki oraz ograniczenia prawa do publicznego odtwarzania utworów muzycznych w ramach platformy HardbanRecords Lab Commercial Music Licensing Platform CMLP. W rozumieniu niniejszego regulaminu Utwór oznacza każde dzieło muzyczne lub fonograficzne włączone do katalogu HRL, stworzone w 100% przez HardbanRecords Lab lub jego współpracowników na podstawie umowy z przeniesieniem praw autorskich. Katalog oznacza kompletną bazę danych utworów dostępnych dla klientów w ramach aktywnej subskrypcji CMLP. Lokal oznacza jednoosobowe miejsce prowadzenia działalności gospodarczej, w którym odtwarzana jest muzyka z katalogu HRL, obejmujące obszar nie większy niż 500 metrów kwadratowych dla lokali gastronomicznych i 1000 metrów kwadratowych dla innych branż. Sieć lokalizacji oznacza zespół co najmniej trzech lokali należących do tego samego podmiotu gospodarczego, korzystających z jednej subskrypcji Enterprise. Licencja oznacza umowę licencyjną między HardbanRecords Lab a Klientem, udzielającą prawa do publicznego odtwarzania utworów w określonych granicach. Panel B2B oznacza dedykowany interfejs internetowy dostępny pod adresem cmlp.hardbanrecordslab.online, służący do zarządzania licencją, playlistami i ustawieniami odtwarzania. Odtwarzanie oznacza każdy sposób publicznego lub prywatnego odtwarzania utworów z katalogu HRL. Publiczne odtwarzanie oznacza odtwarzanie muzyki w miejscu dostępnym dla ogółu publiczności lub dla określonej grupy osób. Podmiot powiązany oznacza każdy podmiot trzecie współpracujący z administratorem. Usługa dodatkowa oznacza każdą usługę świadczoną poza zakresem standardowej subskrypcji, w tym konfiguracja API, szkolenia, konsultacje techniczne oraz usługi Muzyczna Kreacja Słów.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '2. Zakres przyznanej licencji', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab udziela Klientowi niewyłącznej, niepodzielnej, nieprzenoszalnej licencji na publiczne odtwarzanie utworów z katalogu HRL wyłącznie w określonych lokalach określonych w zamówieniu. Licencja obejmuje prawo do odtwarzania muzyki w formie streamingu audio przez dedykowany odtwarzacz CMLP, zarówno w wersji standardowej, jak i white-label. Licencja nie obejmuje prawa do tworzenia utworów pochodnych, remixów,采样 lub innych przekształceń utworów z katalogu. Wszelkie prawa autorskie, prawa wykonawcze oraz prawa majątkowe do utworów pozostają wyłączną własnością HardbanRecords Lab. Licencja nie przenosi żadnych praw własności intelektualnej na Klienta. Zakres licencji rozciąga się na terytorium Rzeczypospolitej Polskiej oraz innych krajów Europejskiego Obszaru Gospodarczego, jeśli Klient wybrał pakiet EEA. W przypadku wyboru pakietu Global, zakres obejmuje wszystkie terytoria gdzie HRL posiada aktywne certyfikaty licencyjne. Licencja nie upoważnia do dystrybucji utworów, publikacji na platformach społecznościowych ani użycia w projektach medialnych bez dodatkowej umowy. Klient zobowiązuje się do korzystania z licencji wyłącznie w zgodzie z jej przeznaczeniem oraz postanowieniami niniejszego regulaminu. Wykorzystanie utworów wykraczające poza zakres licencji wymaga osobnej umowy licencyjnej i podlega dodatkowym opłatom.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '3. Pakiety licencyjne i limity', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Platforma CMLP oferuje następujące pakiety licencyjne różniące się zakresem terytorialnym, liczbą dozwolonych lokalizacji i limitem utworów w katalogu. Pakiet Starter umożliwia odtwarzanie w jednym lokalu, z dostępem do podstawowej biblioteki 10 utworów, w jakości MP3 320kbps. Pakiet Business obejmuje do trzech lokalizacji, 50 utworów w katalogu, priorytetowe wsparcie techniczne oraz miesięczne raporty. Pakiet Premium oferuje do dziesięciu lokalizacji, 200 utworów, dostęp do white-label playera z własną subdomeną, zaawansowanej analityki odtworzeń oraz priorytetowego wsparcia. Pakiet Enterprise stanowi rozwiązanie pełne, obejmujące nieograniczoną liczbę lokalizacji, pełny katalog utworów, dedykowanego opiekuna konta, umowę SLA 99,9% kapowności, pełny dostęp API REST v3 oraz możliwość niestandardowych integracji. Dodatkowo dostępne są pakiety specjalne Event jednorazowa licencja na konkretne wydarzenie z dostępem do 50 utworów oraz Seasonal licencja sezonowa obejmująca 5 lokalizacji i 100 utworów przez okres 3 miesięcy. W przypadku wymagań specyficznych, HardbanRecords Lab oferuje pakiety Custom wyceniane indywidualnie. Wszystkie pakiety obejmują automatyczny Certyfikat Zwolnienia z OZZ dostępny w Panelu B2B.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '4. Okres obowiązywania i automatyczne odnawianie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Każda licencja udzielana jest na okres 12 miesięcy, licząc od daty aktywacji płatności. Licencja odnawia się automatycznie na kolejne okresy 12-miesięczne, chyba że Klient wyraźnie wypowie umowę z 30-dniowym wyprzedzeniem przed końcem bieżącego okresu rozliczeniowego. W przypadku braku wypowiedzenia, płatność za kolejny okres zostanie obciążona automatycznie w dniu rocznicy aktywacji. Klient może w każdej chwili wybrać inny pakiet licencyjny, zmiana wchodzi w życie od następnego okresu rozliczeniowego. W przypadku zmiany planu na mniej kosztowny, różnica kwot jest proporcjonalnie zwracana klientowi w formie kredytu na kolejny okres lub w formie zwrotu na konto bankowe w ciągu 14 dni roboczych. W przypadku opóźnienia płatności o więcej niż 7 dni, dostęp do katalogu może zostać tymczasowo zablokowany do momentu uregulowania zaległej kwoty. Administrator zastrzega sobie prawo do zmiany cen pakietów licencyjnych z 30-dniowym wyprzedzeniem.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '5. White-Label Player szczególne warunki', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Klienci pakietów Premium i Enterprise otrzymują prawo do korzystania z wersji white-label odtwarzacza CMLP dostępnej pod subdomeną wybraną przez Klienta np. muzyka.twojafirma.pl. Klient ma prawo do umieszczenia własnego logo, nazwy handlowej, palety kolorów oraz dostosowania interfejsu użytkownika zgodnie z wytycznymi dostarczonymi przez HardbanRecords Lab. Klient nie ma prawa do dekompilacji, reverse engineering, modyfikacji rdzenia odtwarzacza ani tworzenia konkurujących produktów na bazie white-label playera. HardbanRecords Lab zastrzega sobie prawo do wycofania subdomeny w przypadku naruszenia warunków licencji, wykorzystania odtwarzacza do nielegalnych celów lub powstawania zagrożeń dla bezpieczeństwa infrastruktury platformy. Wszelkie koszty związane z konfiguracją subdomeny, certyfikatem SSL oraz dostosowaniem DNS ponosi Klient. W przypadku pakietów Enterprise, administrator oferuje pomoc przy konfiguracji subdomeny i SSL w ramach usług onboardingowych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '6. API Enterprise dostęp i ograniczenia', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Klienci Enterprise otrzymują dostęp do interfejsu programistycznego API REST v3, umożliwiającego integrację odtwarzacza CMLP z systemami POS, aplikacjami mobilnymi, panelami zarządzania oraz innymi narzędziami biznesowymi Klienta. API udostępniane jest przez HTTPS z wymogiem autoryzacji za pomocą tokenów JWT. HardbanRecords Lab zastrzega sobie prawo do wprowadzania limitów zapytań rate limiting w celu ochrony stabilności infrastruktury. Domyślny limit dla planów Enterprise wynosi 1000 zapytań na godzinę na konto. Klient nie ma prawa do udostępniania tokenów API osobom trzecim, wykorzystywania API do celów nieautoryzowanych, tworzenia konkurencyjnych serwisów na bazie API, ani wykonywania requestów masowych bulk requests mogących obciążyć infrastrukturę. Naruszenie warunków API może skutkować natychmiastowym zablokowaniem dostępu API bez zwrotu opłaty. Administrator zobowiązuje się do powiadamiania klientów o planowanych zmianach w API z co najmniej 30-dniowym wyprzedzeniem. Dokumentacja API dostępna jest pod adresem docs.cmlp.hardbanrecordslab.online po zalogowaniu się do Panelu B2B.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '7. Gwarancje i ograniczenie odpowiedzialności', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab gwarantuje, że wszystkie utwory w katalogu są w 100% autorskie i nie naruszają praw osób trzecich w zakresie, w jakim są wykorzystywane zgodnie z niniejszym regulaminem. W razie stwierdzenia naruszenia praw autorskich przez jakikolwiek utwór w katalogu, Administrator zobowiązuje się do natychmiastowego wycofania utworu z katalogu oraz zwrotu proporcjonalnej części opłaty licencyjnej. HardbanRecords Lab nie gwarantuje jednak, że utwory będą odpowiednie dla konkretnego lokalu lub odbioru, ani że platforma będzie działać bez przerw. Maksymalna odpowiedzialność Administratora wobec Klienta nie przekroczy kwoty opłaty licencyjnej zapłaconej w bieżącym okresie rozliczeniowym. Administrator nie ponosi odpowiedzialności za straty pośrednie, utracone zyski, utratę danych lub inne szkody następcze, nawet jeśli został poinformowany o możliwości ich powstania.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '8. Rozwiązanie umowy licencyjnej', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Umowa licencyjna może zostać rozwiązana przez Klienta w dowolnym momencie z 30-dniowym okresem wypowiedzenia, bez podania przyczyny. Rozwiązanie nie wiąże się z karami finansowymi, o ile Klient zaprzestanie używania licencji po zakończeniu okresu wypowiedzenia. Administrator ma prawo do natychmiastowego rozwiązania umowy w przypadku naruszenia warunków licencji przez Klienta, wykorzystania utworów w sposób niezgodny z przeznaczeniem, próby dekompilacji oprogramowania, opóźnienia płatności o więcej niż 14 dni, lub działania siły wyższej utrudniającego świadczenie usług przez okres przekraczający 30 dni. Po rozwiązaniu umowy, Klient zobowiązany jest do natychmiastowego zaprzestania odtwarzania utworów z katalogu HRL i usunięcia wszystkich skopiowanych plików audio z urządzeń oraz systemów.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '9. Postanowienia dodatkowe', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Umowa licencyjna podlega prawu polskiemu. Wszelkie spory rozstrzygane będą przez sąd właściwy dla siedziby Administratora. W przypadku gdy którekolwiek z postanowień umowy zostanie uznane za nieważne lub niewykonalne, pozostałe postanowienia zachowują ważność. Administrator zastrzega sobie prawo do modyfikacji niniejszego regulaminu w dowolnym momencie. O zmianach poinformuje Klienta z 14-dniowym wyprzedzeniem na adres e-mail powiązany z kontem. Kontynuowanie korzystania z licencji po zmianach uznaje się za akceptację nowych warunków. Wszystkie zapisy regulaminu interpretowane są zgodnie z ich zwykłym znaczeniem w języku polskim, uwzględniając cel regulaminu oraz potrzeby stron w zakresie przejrzystości i zrozumienia postanowień prawnych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '10. Monitoring i egzekucja licencji', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab zastrzega sobie prawo do monitorowania użytkowania licencji w celu zapewnienia zgodności z warunkami umowy. Monitorowanie obejmuje logi odtworzeń, liczbę równoległych sesji, lokalizacje odtwarzania oraz zgodność z wybranym pakietem. W przypadku wykrycia wykroczeń, administrator powiadomi Klienta i wezwie do usunięcia niezgodności w ciągu 7 dni roboczych. Jeśli Klient nie usunie niezgodności w określonym terminie, administrator zastrzega sobie prawo do zawieszenia lub zablokowania dostępu do platformy. W przypadku powtarzających się naruszeń, umowa licencyjna może zostać rozwiązana automatycznie bez zwrotu opłaty za niekorzystany okres. Wszystkie działania egzekucyjne są dokumentowane i udostępniane Klientowi na żądanie.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '11. Przeniesienie praw i obowiązków', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab zastrzega sobie prawo do przenoszenia praw i obowiązków wynikających z umowy licencyjnej na podmiot trzecie w przypadku przejęcia, fuzji lub zmiany formy prawnej, o czym poinformuje Klienta z 14-dniowym wyprzedzeniem. Przeniesienie praw i obowiązków nie wpływa na warunki licencji oraz prawa Klienta. W przypadku nieprawidłowego działania platformy spowodowanego awarią infrastruktury administratora, Klient ma prawo do proporcjonalnego zwrotu opłaty licencyjnej za czas, w którym platforma była niedostępna. Zwrot następuje automatycznie w formie kredytu na kolejny okres rozliczeniowy lub w formie zwrotu na konto bankowe, zgodnie z preferencjami Klienta wyrażonymi w Panelu B2B.', 'hrl-theme' ); ?></p>    <h2><?php esc_html_e( '12. Kontakt w sprawach licencyjnych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W sprawach dotyczących licencjonowania, rozliczeń, konfiguracji API, white-label playera, zmiany pakietu lub jakichkolwiek innych kwestii związanych z umową licencyjną Klient może kontaktować się z HardbanRecords Lab pod adresem e-mail contact@hardbanrecordslab.online, telefonicznie pod numerem +48 726 651 384 lub przez ticket system dostępny w Panelu B2B w zakładce Wsparcie. Administrator udziela odpowiedzi w ciągu 14 dni roboczych, a klienci Enterprise w ciągu 8 godzin roboczych. W przypadku sporów dotyczących wykroczeń licencyjnych, strony zobowiązują się do rozstrzygnięcia na drodze mediacji przed skierowaniem sprawy do sądu.', 'hrl-theme' ); ?></p>

</div>
</div>
<?php get_footer(); ?>