<?php
/**
 * Template Name: Klauzula RODO
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<div class="legal-page-wrapper">
<div class="legal-content">
    <h1><?php esc_html_e( 'Klauzula Informacyjna RODO', 'hrl-theme' ); ?></h1>
    <p class="legal-date"><?php esc_html_e( 'Ostatnia aktualizacja: 12 lipca 2026 r.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '1. Wprowadzenie i zakres', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Niniejsza klauzula informacyjna została przygotowana zgodnie z art. 13 i art. 14 Rozporządzenia Parlamentu Europejskiego i Rady UE 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE ogólne rozporządzenie o ochronie danych dalej RODO. Klauzula dotyczy wszystkich form przetwarzania danych osobowych realizowanych przez HardbanRecords Lab w ramach świadczenia usług licencjonowania muzyki komercyjnej, obsługi klientów B2B, prowadzenia działalności gospodarczej oraz realizacji obowiązków prawnych. Niniejsza klauzula uzupełnia Politykę Prywatności dostępną pod adresem /privacy/ i powinna być czytana łącznie z całą dokumentacją prawną platformy.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '2. Podmiot przetwarzający dane', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Administratorem danych osobowych przetwarzanych w ramach platformy CMLP i powiązanych serwisów jest HardbanRecords Lab, przedsiębiorstwo świadczące usługi w zakresie licencjonowania muzyki komercyjnej, zainteresowani w zakresie ochrony danych osobowych zgodnie z RODO. HardbanRecords Lab działa zarówno jako administrator danych w zakresie danych użytkowników platformy, klientów B2B, subskrybentów newslettera oraz osób kontaktujących się przez formularze, jak również jako podmiot przetwarzający dane w zakresie logów systemowych i danych telemetrycznych. W przypadku pytań dotyczących przetwarzania danych osobowych prosimy o kontakt pod adresem contact@hardbanrecordslab.online lub telefonicznie pod numerem +48 726 651 384. Administrator wyznaczył wewnętrznego inspektora ochrony danych IOD dostępnego pod adresem iod@hardbanrecordslab.online.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '3. Cele i podstawy prawne przetwarzania', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Dane osobowe przetwarzane są w następujących celach i na podstawie następujących podstaw prawnych: a Realizacja umowy licencyjnej B2B podstawą prawną jest art. 6 ust. 1 lit. b RODO wykonanie umowy. Obejmuje to dane identyfikacyjne klienta nazwa firmy NIP adres dane kontaktowe osoby upoważnionej, dane do faktury regon dane adresowe, dane logowania do Panelu B2B, dane dotyczące licencji okres obowiązywania zakres lokalizacje. b Obsługa płatności i rozliczeń podstawą prawną jest art. 6 ust. 1 lit. b RODO wykonanie umowy oraz art. 6 ust. 1 lit. c RODO obowiązek prawny. Obejmuje to dane transakcji historię płatności dane do faktur referencje płatnicze. c Wysyłka newslettera podstawą prawną jest art. 6 ust. 1 lit. a RODO zgoda. Obejmuje imię nazwisko adres e-mail preferencje dotyczące treści newslettera. Zgoda może być wycofana w dowolnym momencie. d Analiza statystyczna i ulepszanie usług podstawą prawną jest art. 6 ust. 1 lit. f RODO prawnie uzasadniony interes. Obejmuje anonimowe dane telemetryczne logi odtworzeń preferencje muzyczne statystyki korzystania z platformy. e Zaspokojenie prawnie uzasadnionego interesu administratora podstawą prawną jest art. 6 ust. 1 lit. f RODO. Obejmuje weryfikację tożsamości zapobieganie oszustwom zapewnienie bezpieczeństwa sieci ochrona przed nadużyciami. f Obowiązki raportowe i księgowe podstawą prawną jest art. 6 ust. 1 lit. c RODO obowiązek prawny. Obejmuje dane niezbędne do wypełnienia obowiązków podatkowych i księgowych wynikających z przepisów ustawy o rachunkowości oraz ustawy o podatku od towarów i usług. g Marketing bezpośredni podstawą prawną jest art. 6 ust. 1 lit. a RODO zgoda na marketing lub art. 6 ust. 1 lit. f RODO prawnie uzasadniony interes w przypadku klientów biznesowych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '4. Kategorie odbiorców danych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Dane osobowe mogą być udostępniane następującym kategoriom odbiorców: podmioty obsługujące płatności Stripe Payments Europe Limited PayPal Pte. Ltd. PayU S.A., podmioty świadczące usługi hostingowe i infrastrukturalne DigitalOcean LLC Hetzner Online GmbH Amazon Web Services Inc., podmioty świadczące usługi pocztowe i kurierskie do wysyłki faktur papierowych, podmioty świadczące usługi księgowe i audytowe, instytucje publiczne uprawnione do żądania danych na podstawie przepisów prawa, podmioty świadczące usługi wsparcia technicznego Zendesk Inc. Freshworks Inc. oraz inne podmioty, wobec których administrator ma obowiązek udostępnienia danych na podstawie obowiązujących przepisów prawa. Wszyscy podmioty przetwarzające dane osobowe w imieniu administratora zobowiązani są do przestrzegania RODO i innych przepisów o ochronie danych osobowych oraz podpisują umowy powierzenia przetwarzania danych przed rozpoczęciem współpracy. Administrator prowadzi rejestr podmiotów przetwarzających dane w imieniu administratora dostępny na żądanie.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '5. Prawa osoby której dane dotyczą', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Każda osoba, której dane osobowe są przetwarzane przez HardbanRecords Lab, ma następujące prawa wynikające z RODO: prawo dostępu do danych osobowych możliwość uzyskania potwierdzenia, czy dane osobowe są przetwarzane, oraz dostępu do ich treści; prawo do sprostowania możliwość poprawienia nieprawidłowych danych oraz uzupełnienia niekompletnych; prawo do usunięcia prawo do bycia zapomnianym możliwość żądania usunięcia danych, jeśli nie są już niezbędne do celów, dla których były zbierane, lub jeśli osoba wycofała zgodę; prawo do ograniczenia przetwarzania możliwość żądania ograniczenia przetwarzania w przypadkach wątpliwości co do prawidłowości danych, nieprawidłowości przetwarzania lub gdy dane są niezbędne do ustalenia, dochodzenia lub obrony roszczeń; prawo do przenoszenia danych możliwość otrzymania danych osobowych w formacie strukturyzowanym, powszechnie używanym i maszynowo czytelnym, oraz przeniesienia ich do innego administratora; prawo do sprzeciwu możliwość sprzeciwu wobec przetwarzania danych w celach marketingu bezpośredniego lub w celach naukowych historycznych statystycznych; prawo do wycofania zgody jeśli przetwarzanie opiera się na zgodzie, osoba może ją wycofać w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania dokonanego przed wycofaniem; prawo wniesienia skargi każda osoba ma prawo wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych PUODO na adres ul. Stawki 2, 00-193 Warszawa, jeśli uważa, że przetwarzanie danych osobowych narusza przepisy RODO.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '6. Sposób realizacji praw', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Aby skorzystać z praw wynikających z RODO, należy skontaktować się z administratorem przez formularz kontaktowy na stronie /contact/, wysłać wiadomość e-mail na adres contact@hardbanrecordslab.online lub zadzwonić pod numer +48 726 651 384. W zapytaniu należy podać pełne imię i nazwisko lub nazwę firmy, adres e-mail lub telefon, opis żądania oraz dokumentację tożsamości jeśli wymagana. Administrator potwierdza otrzymanie zapytania w ciągu 3 dni roboczych i udziela odpowiedzi w ciągu 14 dni roboczych. W uzasadnionych przypadkach termin może zostać przedłużony o kolejne 14 dni, o czym administrator informuje użytkownika przed upływem pierwotnego terminu. Realizacja praw jest bezpłatna, chyba że żądanie jest oczywiście nieuzasadnione lub nadmierne, w szczególności ze względu na powtarzający się charakter. W takim przypadku administrator może pobrać rozsądną opłatę lub odmówić zrealizowania żądania.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '7. Okres przechowywania danych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Dane osobowe są przechowywane przez okres nie dłuższy, niż jest to niezbędne do celów, dla których są przetwarzane. Okresy przechowywania dla poszczególnych kategorii danych: Dane klientów B2B identyfikacyjne kontaktowe fakturowe przez okres obowiązywania umowy licencyjnej oraz 5 lat po jej zakończeniu, zgodnie z okresem przedawnienia roszczeń wynikających z przepisów ustawy o rachunkowości. Dane płatności i transakcje przez okres obowiązywania umowy oraz 5 lat po jej zakończeniu, zgodnie z wymaganiami podatkowymi i regulacjami podmiotów płatniczych. Logi systemowe i telemetria przez okres 12 miesięcy od zdarzenia, chyba że przepisy prawa wymagają dłuższego okresu. Zgody marketingowe przez okres obowiązywania zgody, do momentu wycofania lub cofnięcia zgody przez administratora. Po upływie okresów przechowywania dane są trwale usuwane lub anonimizowane. W przypadku procesów prawnych, okres przechowywania danych może zostać przedłużony zgodnie z obowiązującymi przepisami.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '8. Prawa do sprzeciwu i wycofania zgody', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Każda osoba, której dane osobowe są przetwarzane przez HardbanRecords Lab, ma prawo w dowolnym momencie wnieść sprzeciw wobec przetwarzania jej danych osobowych w celach marketingu bezpośredniego, w tym tworzenia profili użytkownika. Sprzeciw powinien zostać złożony na piśmie, wysłany na adres contact@hardbanrecordslab.online, z wyraźnym zaznaczeniem, że dotyczy sprzeciwu wobec marketingu bezpośredniego. Administrator zatrzymuje przesyłanie komunikacji marketingowej do osoby w ciągu 72 godzin od otrzymania sprzeciwu. Sprzeciw nie wpływa na zgodność z prawem przetwarzania danych dokonanego przed wniesieniem sprzeciwu. W przypadku gdy osoba skorzystała z prawa do sprzeciwu, jej dane nie będą już wykorzystywane do celów marketingowych, ale mogą być nadal przetwarzane w celach związanych z wykonywaniem umów lub obowiązków prawnych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '9. Bezpieczeństwo przetwarzania danych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab stosuje odpowiednie środki techniczne i organizacyjne w celu zabezpieczenia danych osobowych przed utratą, zniszczeniem, nieautoryzowanym dostępem, ujawnieniem lub modyfikacją. Środki bezpieczeństwa obejmują: szyfrowanie wszystkich transmisji danych za pomocą protokołu TLS 1.3 z certyfikatami SSL, hashowanie haseł użytkowników za pomocą algorytmu bcrypt z losową solą, izolację środowisk produkcyjnych za pomocą kontenerów Docker, regularne kopie zapasowe bazy danych przechowywane w bezpiecznych lokalizacjach, monitorowanie dostępu do systemów za pomocą narzędzi Uptime Kuma oraz Sentry, uwierzytelnianie dwuskładnikowe dla wszystkich użytkowników Panelu B2B, restrykcyjne uprawnienia systemowe na serwerach produkcyjnych oraz regularne audyty bezpieczeństwa przeprowadzane przez zewnętrznych ekspertów. W razie stwierdzenia naruszenia bezpieczeństwa danych osobowych, administrator niezwłocznie powiadomi odpowiedni organ nadzorczy oraz dotkniętych użytkowników zgodnie z obowiązującymi przepisami prawa.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '10. Kontakt w sprawach ochrony danych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W sprawach dotyczących przetwarzania danych osobowych, realizacji praw wynikających z RODO oraz zgłaszania naruszeń bezpieczeństwa danych, prosimy o kontakt pod adresem e-mail contact@hardbanrecordslab.online, telefonicznie pod numerem +48 726 651 384 lub pisemnie na adres siedziby HardbanRecords Lab. Administrator udziela odpowiedzi na zapytania i skargi w ciągu 14 dni roboczych od dnia otrzymania zapytania. W uzasadnionych przypadkach termin może zostać przedłużony o kolejne 14 dni, o czym administrator informuje użytkownika przed upływem pierwotnego terminu. Realizacja praw i odpowiedź na zapytania jest bezpłatna. Administrator nie pobiera opłat za realizację żądań dotyczących danych osobowych, chyba że żądanie jest oczywiście nieuzasadnione lub nadmierne.', 'hrl-theme' ); ?></p>    <p><?php esc_html_e( 'Niniejsza klauzula informacyjna stanowi integralną część polityki prywatności platformy HardbanRecords Lab i reguluje wszystkie aspekty przetwarzania danych osobowych realizowanego przez administratora w ramach świadczenia usług B2B. W przypadku rozbieżności między niniejszą klauzulą a innymi dokumentami prawnymi platformy, stosuje się przepisy niniejszej klauzuli jako dokumentu nadrzędnego w zakresie ochrony danych osobowych. Administrator zastrzega sobie prawo do aktualizacji niniejszej klauzuli w dowolnym momencie z przyczyn uzasadnionych, o czym poinformuje użytkowników z 14-dniowym wyprzedzeniem.', 'hrl-theme' ); ?></p>    <p><?php esc_html_e( 'Wszelkie pytania dotyczące niniejszej klauzuli lub polityki prywatności można kierować do administratora pod adresem e-mail contact@hardbanrecordslab.online. Jesteśmy do dyspozycji i pomożemy Ci w każdej kwestii dotyczącej ochrony danych osobowych oraz przetwarzania informacji na platformie HardbanRecords Lab.', 'hrl-theme' ); ?></p>


</div>
</div>
<?php get_footer(); ?>