<?php
/**
 * Template Name: Regulamin
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<div class="legal-page-wrapper">
<div class="legal-content">
    <h1><?php esc_html_e( 'Regulamin Świadczenia Usług', 'hrl-theme' ); ?></h1>
    <p class="legal-date"><?php esc_html_e( 'Ostatnia aktualizacja: 12 lipca 2026 r.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '1. Postanowienia ogólne', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Niniejszy regulamin określa szczegółowe zasady korzystania z całego ekosystemu platformy HardbanRecords Lab, obejmującego między innymi serwis CMLP Commercial Music Licensing Platform, platformę HRL BlogCast, Radio HRL oraz narzędzie Muzyczna Kreacja Słów. Regulamin stanowi podstawę prawną relacji między administratorem platformy a każdym użytkownikiem, niezależnie od formy korzystania z usług, zakładania konta lub nawiązywania jakichkolwiek relacji prawnych z HardbanRecords Lab.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Wszystkie postanowienia regulaminu mają charakter obowiązkujący dla wszystkich użytkowników, którzy przystępują do korzystania z platformy, tworzą konto użytkownika, składają zamówienie na usługi licencyjne, zapisują się na newsletter, skontaktują się z administratorem za pomocą formularzy kontaktowych lub w jakikolwiek inny sposób korzystają z oferowanych usług. Korzystanie z platformy w jakikolwiek sposób oznacza pełną akceptację regulaminu. Jeśli użytkownik nie zgadza się z jakimkolwiek postanowieniem regulaminu, powinien natychmiast zaprzestać korzystania z platformy i usunąć swoje konto użytkownika o ile zostało założone.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'HardbanRecords Lab zastrzega sobie prawo do modyfikacji regulaminu w dowolnym momencie z przyczyn uzasadnionych — w szczególności zmianami w przepisach prawa, rozwojem technologii, wprowadzaniem nowych funkcji platformy lub dostosowaniem regulaminu do wytycznych organów nadzorczych. O każdej zmianie regulaminu administrator poinformuje użytkowników co najmniej na 14 dni roboczych przed wejściem zmian w życie, poprzez opublikowanie nowej wersji regulaminu na stronie internetowej oraz wysłanie powiadomienia na adres e-mail powiązany z kontem użytkownika. Kontynuowanie korzystania z platformy po wprowadzeniu zmian oznacza akceptację nowych postanowień regulaminu.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Platforma HardbanRecords Lab stanowi zintegrowane rozwiązanie technologiczne łączące sztuczną inteligencję, automatyzację procesów biznesowych oraz bazę danych autorskich utworów muzycznych, co pozwala klientom na skalowanie działalności bez dodatkowych kosztów związanych z organizacjami zbiorowymi. Celem strategicznym administratora jest zbudowanie największej w Europie biblioteki muzyki komercyjnej wolnej od tantiem i opłat zbiorowych, dostępnej dla każdego przedsiębiorcy bez względu na wielkość jego działalności.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Regulamin niniejszy odzwierciedla wartości transparentności, bezpieczeństwa, innowacyjności oraz poszanowania praw autorskich, które kierują działalnością HardbanRecords Lab na rynku globalnym. Wszystkie zapisy regulaminu interpretowane są zgodnie z ich zwykłym znaczeniem w języku polskim, uwzględniając cel regulaminu oraz potrzeby stron w zakresie przejrzystości i zrozumienia postanowień prawnych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '2. Zakres usług i ich charakter', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab świadczy szerokie spektrum usług w zakresie tworzenia, licencjonowania i dystrybucji muzyki oryginalnej oraz narzędzi wspierających branżę kreatywną. Oferta usług obejmuje przede wszystkim platformę Commercial Music Licensing Platform CMLP, która umożliwia przedsiębiorcom, właścicielom lokali gastronomicznych, hotelarstwu, sieciom handlowym oraz organizatorom wydarzeń legalne publiczne odtwarzanie kompletnej biblioteki utworów 100% autorskich w zamian za miesięczną lub roczną opłatę abonamentową.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Oferta rozszerza się również o usługę Muzyczna Kreacja Słów, która umożliwia zamawianie personalizowanych utworów na konkretne potrzeby klienta — tak jak muzyka na wesele, ścieżka dźwiękowa do filmu, jingle reklamowy czy utwór na wydarzenie firmowe. Dodatkowo administrator świadczy usługi związane z streamingu radiowym poprzez Radio HRL, które nadaje wyłącznie muzykę autorską z katalogu HRL w jakości profesjonalnej, skierowanej do członków społeczności HRL oraz publiczności ogólnej.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Platforma edukacyjna BlogCast oferuje artykuły, wywiady, analizy rynkowe oraz poradniki dotyczące branży muzycznej i licencjonowania. HardbanRecords Lab zastrzega sobie prawo do rozszerzania zakresu świadczonych usług o nowe produkty cyfrowe, narzędzia sztucznej inteligencji, płatne szkolenia oraz usługi konsultingowe, o czym użytkowników będzie informował z odpowiednim wyprzedzeniem.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Platforma CMLP opiera się na architekturze mikroserwisowej z wykorzystaniem stacku technologicznego obejmującego Node.js, Express.js, PostgreSQL jako główną bazę danych, Redis jako cache i kolejkowanie zadań, Nginx jako reverse proxy, Docker i Docker Compose jako narzędzia orkiestracji kontenerów, oraz Let’s Encrypt do certyfikatu SSL. Klient korzysta z usługi przy użyciu dedykowanego Panelu B2B dostępnego pod adresem cmlp.hardbanrecordslab.online, umożliwiającego zarządzanie licencją, tworzenie playlist, zarządzanie urządzeniami odtwarzającymi oraz przeglądanie analityki odtworzeń. Wszystkie funkcje Panelu B2B są dostępne z urządzeń mobilnych i desktopowych z dowolnej przeglądarki internetowej spełniającej standardy bezpieczeństwa.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '3. Rejestracja i konto użytkownika', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W celu skorzystania z pełni funkcji platformy wymagana jest rejestracja konta użytkownika. Proces rejestracji wymaga podania prawdziwych danych osobowych lub firmowych, w tym imienia i nazwiska lub nazwy firmy, adresu e-mail, hasła dostępu oraz danych niezbędnych do wystawiania faktur w przypadku klientów biznesowych.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Użytkownik zobowiązany jest do podawania wyłącznie prawdziwych, aktualnych i pełnych danych oraz do ich natychmiastowej aktualizacji w przypadku jakichkolwiek zmian. HardbanRecords Lab nie ponosi odpowiedzialności za konsekwencje podania nieprawdziwych lub niekompletnych danych przez użytkownika, w tym za niemożność świadczenia usług, opóźnienia w wysyłce korespondencji lub problemy z rozliczeniami finansowymi.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Użytkownik jest wyłącznie odpowiedzialny za zachowanie poufności danych logowania do konta, w tym hasła, adresu e-mail oraz kodu weryfikacyjnego dwuskładnikowej autoryzacji. Użytkownik zobowiązany jest do niezwłocznego powiadomienia administratora o każdym przypadku utraty, kradzieży lub nieautoryzowanego użytkowania danych logowania do konta. HardbanRecords Lab zastrzega sobie prawo do zawieszenia lub trwałego zablokowania konta użytkownika, który narusza postanowienia regulaminu, podaje fałszywe dane, podejmuje próby hackingu, ataków DDoS, nadużycia systemu płatności lub działa na szkodę innych użytkowników lub administratora.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Proces tworzenia konta w Panelu B2B obejmuje następujące etapy: wypełnienie formularza rejestracyjnego z danymi firmy i osoby kontaktowej, weryfikację adresu e-mail przez wysłanie linku aktywacyjnego, podanie danych niezbędnych do rozliczeń, akceptację regulaminu i polityki prywatności oraz opcjonalne skonfigurowanie uwierzytelniania dwuskładnikowego za pomocą aplikacji Google Authenticator lub innego kompatybilnego narzędzia TOTP. Administrator zatrzymuje dane osobowe użytkownika przez okres obowiązywania umowy licencyjnej oraz okres przedawnienia wynikający z przepisów o rachunkowości, zgodnie z obowiązującymi regułami przechowywania danych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '4. Obowiązki Użytkownika', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Każdy użytkownik platformy HardbanRecords Lab zobowiązany jest do przestrzegania następujących zasad obowiązkowych: podawania wyłącznie prawdziwych danych osobowych lub firmowych podczas rejestracji konta oraz podczas każdej interakcji z administratorem lub systemem platformy; nieudostępniania swoich danych logowania do konta osobom trzecim pod żadnym pozorem, nawet tym z własnego zespołu lub rodziny; zgłaszania każdego przypadku nieautoryzowanego dostępu do konta lub podejrzenia naruszenia bezpieczeństwa niezwłocznie po stwierdzeniu takiego zdarzenia; korzystania z platformy wyłącznie w sposób zgodny z przeznaczeniem, obowiązującymi przepisami prawa Rzeczypospolitej Polskiej oraz postanowieniami niniejszego regulaminu; niepodejmowania żadnych działań mogących zakłócać funkcjonowanie platformy, w tym ataków DDoS, prób injectowania kodu SQL, wykorzystywania luk w zabezpieczeniach, nadużywania zasobów systemowych, wysyłania niechcianego spamu przez formularze kontaktowe; przestrzegania polskiego prawa autorskiego, prawa konkurencji, przepisów o ochronie danych osobowych oraz wszystkich innych obowiązujących przepisów prawa w zakresie świadczonych usług. Użytkownik ponosi pełną odpowiedzialność za wszystkie działania podejmowane za pośrednictwem swojego konta lub adresu IP.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Użytkownik ma obowiązek regularnego sprawdzania aktualizacji regulaminu dostępnych na stronie internetowej platformy oraz porozumienie z zmianami funkcjonalnymi platformy ogłaszanymi w Panelu B2B lub w newsletterze. Użytkownik zobowiązany się do niepodejmowania żadnych działań mających na celu reverse engineering, dekompilację, montaż, tłumaczenie ani w jakikolwiek sposób modyfikowanie oprogramowania platformy, w tym odtwarzacza CMLP, interfejsu API, pluginu WordPress integrującego platformę z witryną klienta. Użytkownik nie ma prawa do używania nazwy handlowej HardbanRecords Lab, znaku towarowego HRL, logo ani jakichkolwiek innych znaków towarowych administratora bez wyraźnej pisemnej zgody.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '5. Licencje i prawa autorskie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Wszystkie utwory muzyczne, teksty, kompozycje oraz powiązane materiały dostępne na platformie HardbanRecords Lab są w 100% oryginalne i należą wyłącznie do administratora lub zostały stworzone w ramach umowy z przeniesieniem pełnych praw autorskich na HardbanRecords Lab. Klient otrzymuje niewyłączną, niezbywalną licencję na publiczne odtwarzanie utworów w konkretnym, zamówionym lokalu lub lokalizacjach zgodnych z wybranym pakietem licencyjnym. Licencja obejmuje prawo do odtwarzania utworów przez system streamingowy CMLP w ramach przypisanej lokalizacji, w celach komercyjnych lub niekomercyjnych, zgodnie z wybranym pakietem. Licencja nie obejmuje prawa do dystrybucji utworów osobom trzecim, tworzenia remixów lub utworów pochodnych, przekazywania plików audio osobom trzecim, używania utworów w filmach, reklamach, transmisjach na żywo czy innych projektach medialnych bez dodatkowej, osobnej umowy licencyjnej. Wszystkie licencje są wolne od opłat na rzecz organizacji zbiorowego zarządzania prawami autorskimi ZAiKS, STOART, ZPAV, SAWP, co stanowi jedną z głównych przewag oferowanej przez HardbanRecords Lab usługi.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'W przypadku gdy klient zamierza wykorzystać utwór z katalogu HRL w projekcie medialnym, filmie, reklamie, transmisji na żywo, streamingu internetowym lub innym kontekście wykraczającym poza zakres standardowej licencji B2B, zobowiązany jest do wcześniejszego skontaktowania się z administratorem w celu uzyskania odrębnej umowy licencyjnej. HardbanRecords Lab zastrzega sobie prawo do odmowy wydania dodatkowej licencji, jeśli wykorzystanie utworu w proponowanym kontekście może naruszać wartości marki administratora lub generować ryzyko reputacyjne. Wszystkie dodatkowe licencje są wyceniane indywidualnie w zależności od zasiegu, formatu, czasu trwania kampanii i kontekstu wykorzystania.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '6. Płatności, subskrypcje i rozliczenia', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Opłaty za usługi licencyjne oraz inne usługi płatne pobierane są z góry, zgodnie z wybranym cyklem rozliczeniowym miesięcznym lub rocznym. Wszystkie ceny podane są w złotych polskich PLN i zawierają pełną kwotę podatku VAT zgodnie z obowiązującymi przepisami o podatku od towarów i usług. Płatności są realizowane wyłącznie za pośrednictwem zaufanych certyfikowanych operatorów płatności elektronicznych, w tym Stripe Payments Europe Limited, PayPal Pte. Ltd. oraz PayU S.A. HardbanRecords Lab nie przetwarza danych kart płatniczych na własnych serwerach, a wszystkie transakcje finansowe odbywają się na bezpiecznych platformach spełniających wymagania PCI DSS. W przypadku opóźnienia płatności o więcej niż 7 dni od terminu wymagalności, administrator zastrzega sobie prawo do zawieszenia dostępu do platformy i katalogu utworów do momentu uregulowania zaległej kwoty. W przypadku opóźnienia płatności o więcej niż 14 dni, umowa licencyjna może zostać rozwiązana automatycznie. HardbanRecords Lab wystawia faktury w formie elektronicznej na adres e-mail wskazany przez klienta w panelu B2B. W przypadku potrzeby wystawienia faktury w formie papierowej, klient zobowiązany jest do złożenia osobnego żądania z opłatą dodatkową zgodną z cennikiem usług dodatkowych.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Administrator oferuje różne metody płatności dostosowane do potrzeb klientów biznesowych: przelew bankowy tradycyjny dla klientów preferujących płatności prolongatowe za pomocą BLIK dla płatności natychmiastowych, kartami kredytowymi i debetowymi Visa Mastercard American Express, PayPal dla płatności międzynarodowych oraz PayU jako agregator płatności dla klientów z preferencjami dotyczącymi rat. Wszystkie płatności są rozliczane automatycznie i potwierdzone w Panelu B2B. W przypadku błędnego obciążenia konta, klient ma prawo do wniesienia reklamacji w ciągu 14 dni od daty transakcji. Administrator zwraca kwotę błędnego obciążenia w ciągu 7 dni roboczych od potwierdzenia reklamacji.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '7. Reklamacje i odpowiedzialność', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab dokłada wszelkich starań, aby platforma działała nieprzerwanie i bezbłędnie, osiągając cel ciągłości działania na poziomie 99,9% uptime w ciągu każdego miesiąca kalendarzowego. Administrator nie ponosi jednak odpowiedzialności za przerwy w działaniu platformy wynikające z przyczyn niezależnych, w tym działania siły wyższej, awarii infrastruktury zewnętrznej dostawców VPS, CDN lub operatorów płatności, awarii własnych serwerów podczas planowanych aktualizacji konserwacyjnych ogłaszanych z wyprzedzeniem, jak również za szkody wynikające z nieprawidłowego korzystania z platformy przez użytkownika. Klient zobowiązany jest do zgłaszania wszelkich usterek i błędów w działaniu platformy niezwłocznie po ich stwierdzeniu za pośrednictwem formularza kontaktowego lub adresu e-mail support@hardbanrecordslab.online. Administrator zobowiązuje się do rozpatrzenia każdej reklamacji w ciągu 14 dni roboczych i powiadomienia użytkownika o wyniku postępowania. Maximum odpowiedzialności administratora wobec klienta nie przekroczy kwoty opłaty licencyjnej zapłaconej przez klienta w bieżącym okresie rozliczeniowym. Administrator nie ponosi odpowiedzialności za straty pośrednie, utracone zyski, utratę danych lub inne szkody następcze, nawet jeśli został poinformowany o możliwości ich powstania.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'W przypadku gdy klient stwierdzi, że platforma działa z poważną usterką blokującą normalne korzystanie z usługi, administrator zobowiązuje się do podjęcia działań naprawczych w trybie priorytetowym w ciągu 4 godzin roboczych od otrzymania zgłoszenia. W przypadku klientów z pakietem Enterprise, obowiązuje poziom usługi SLA zgodny z warunkami indywidualnej umowy, obejmujący maksymalny czas reakcji na incydenty krytyczne na poziomie 1 godziny, a niekrytycznych 8 godzin roboczych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '8. Postanowienia końcowe', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W sprawach nieuregulowanych niniejszym regulaminem zastosowanie mają przepisy prawa polskiego, w szczególności Kodeksu Cywilnego, ustawy o świadczeniu usług drogą elektroniczną, ustawy o prawach konsumentów, ustawy o ochronie danych osobowych oraz inne obowiązujące akty prawne. Wszelkie spory wynikłe z związane z korzystaniem z platformy lub wykonaniem regulaminu rozstrzygane będą w pierwszej kolejności na drodze negocjacji między stronami. Jeśli strony nie dojdą do porozumienia przez okres 30 dni, sprawa zostanie skierowana do sądu powszechnego właściwego dla siedziby administratora HardbanRecords Lab. W przypadku gdy którekolwiek z postanowień regulaminu zostanie uznane za nieważne lub niewykonalne przez sąd lub organ administracji publicznej, pozostałe postanowienia zachowują pełną ważność. Niezależność poszczególnych postanowień regulaminu oznacza, że uchylenie jednego z nich nie wpływa na obowiązywanie pozostałych. Administrator zastrzega sobie prawo do zaprzestania świadczenia wybranych usług z 30-dniowym wyprzedzeniem powiadomienia użytkowników.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Niniejszy regulamin wchodzi w życie z dniem 12 lipca 2026 roku i zastępuje wszystkie wcześniejsze wersje regulaminu platformy HardbanRecords Lab. Wersje archiwalne regulaminu dostępne są na życzenie klientów biznesowych poprzez kontakt z działem obsługi klienta pod adresem support@hardbanrecordslab.online. W przypadku rozbieżności między wersją regulaminu dostępną na stronie internetowej a wersją wysłaną do klienta w formie elektronicznej, stosuje się wersję aktualnie opublikowaną na stronie internetowej platformy.', 'hrl-theme' ); ?></p>
</div><!-- .legal-content -->
</div><!-- .legal-page-wrapper -->
<?php get_footer(); ?>
