<?php
/**
 * Template Name: Polityka Cookies
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<div class="legal-page-wrapper">
<div class="legal-content">
    <h1><?php esc_html_e( 'Polityka Cookies', 'hrl-theme' ); ?></h1>
    <p class="legal-date"><?php esc_html_e( 'Ostatnia aktualizacja: 12 lipca 2026 r.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '1. Czym są pliki cookie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Pliki cookie to małe, szyfrowane fragmenty danych tekstowych przesyłane przez przeglądarkę internetową i zapisywane na urządzeniu końcowym użytkownika, takim jak komputer, tablet lub telefon smartfon. Służą głównie do rozpoznawania urządzenia podczas kolejnych wizyt na tej samej stronie internetowej, co umożliwia świadczenie spersonalizowanych treści, zapisanie preferencji użytkownika oraz zbieranie danych statystycznych dotyczących sposobu korzystania z serwisu. Pliki cookie mogą być tymczasowe tzw. sesyjne, automatycznie usuwane po zamknięciu przeglądarki oraz stałe, przechowywane przez określony czas lub do momentu ręcznego usunięcia przez użytkownika. Na platformie HardbanRecords Lab cookie wykorzystywane są w sposób minimalizujący i zgodny z RODO oraz wytycznymi Europejskiego Urzędu Ochrony Danych. Każdy użytkownik ma pełną kontrolę nad cookie i może je w dowolnym momencie modyfikować lub usuwać przez ustawienia przeglądarki lub panel zgód dostępny na stronie.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '2. Podstawa prawna przetwarzania', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Przetwarzanie danych za pomocą plików cookie opiera się na prawnie uzasadnionym interesie administratora art. 6 ust. 1 lit. f RODO w zakresie cookie ściśle niezbędnych do świadczenia usługi, jak również na zgodzie użytkownika art. 6 ust. 1 lit. a RODO w zakresie cookie analitycznych, preferencyjnych i marketingowych. Każdy użytkownik ma prawo do wycofania zgody w dowolnym momencie, co jednak nie wpływa na zgodność z prawem przetwarzania dokonanego przed wycofaniem. Administrator jest zobowiązany do świadczenia przejrzystych informacji o każdym rodzaju cookie, jego przeznaczeniu, okresie ważności oraz podmiocie ustawiającym cookie. Wszystkie informacje te udostępniane są w niniejszej polityce oraz w panelu zgód cookie, który pojawia się podczas pierwszej wizyty na stronie. Panel zgód został zaprojektowany zgodnie z wytycznymi EDPB i umożliwia wybiórczą zgodę na różne kategorie plików cookie bez wymogu akceptowania wszystkich jednocześnie.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '3. Rodzaje plików cookie używanych na platformie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Cookie niezbędne strictly necessary są to pliki cookie niezbędne do prawidłowego funkcjonowania strony internetowej, umożliwiające nawigację po stronie oraz dostęp do zabezpieczonych obszarów takich jak Panel B2B i formularze kontaktowe. Bez tych plików strona nie może działać poprawnie. Administrator nie wymaga zgody na te pliki, ponieważ są one niezbędne do świadczenia usługi na żądanie użytkownika. Przykładami cookie niezbędnych są sesje logowania WordPress wordpress hash oraz cookie bezpieczeństwa CSRF token. Cookie preferencyjne preference pozwalają na zapisanie wyborów użytkownika, takich jak język interfejsu, region, rozmiar czcionki, preferencje dotyczące kontrastu lub innych ustawień interfejsu. Umożliwiają dostosowanie strony do indywidualnych potrzeb użytkownika, co podnosi komfort korzystania z platformy. Bez tych plików strona może działać, ale niektóre funkcje personalizacji mogą być niedostępne. Cookie analityczne statistics zbierają anonimowe dane dotyczące sposobu, w jaki użytkownik porusza się po stronie internetowej, które strony odwiedza, ile czasu spędza na każdej z nich oraz jakie błędy napotyka. Wszystkie dane są zbierane w formie zanonimizowanej i nie mogą być użyte do identyfikacji konkretnego użytkownika. Pomagają administratorowi w stałym doskonaleniu struktury i zawartości strony. Cookie marketingowe marketing służą do wyświetlania reklam dostosowanych do zainteresowań użytkownika, do mierzenia efektywności kampanii reklamowych oraz do ograniczenia liczby wyświetleń tej samej reklamy. Może to obejmować pliki cookie używane przez sieci reklamowe do tworzenia profili użytkowników. Wymagają one wyraźnej świadomej zgody użytkownika przed rozpoczęciem ich ustawiania w przeglądarce.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '4. Szczegółowy wykaz plików cookie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Poniższa tabela zawiera szczegółowy wykaz wszystkich plików cookie używanych na platformie HardbanRecords Lab, wraz z ich przeznaczeniem, okresem ważności oraz podstawą prawną ich stosowania. Nazwa cookie wordpress hash służy do sesji logowania do panelu WordPress, okres ważności 14 dni, kategoria niezbędne, podstawa prawna art. 6 ust. 1 lit. f RODO. Nazwa cookie wp-settings user służy do zapisania preferencji interfejsu WP, okres ważności 1 rok, kategoria preferencyjne, podstawa prawna art. 6 ust. 1 lit. a RODO. Nazwa cookie ga służy do Google Analytics, okres ważności 2 lata, kategoria analityczne, podstawa prawna art. 6 ust. 1 lit. a RODO po wyrażeniu zgody. Nazwa cookie gid służy do Google Analytics, okres ważności 24 godziny, kategoria analityczne, podstawa prawna art. 6 ust. 1 lit. a RODO po wyrażeniu zgody. Nazwa cookie hrl consent służy do zapisania wyborów użytkownika dotyczących zgód na cookie, okres ważności 1 rok, kategoria niezbędne do zarządzania zgodami, podstawa prawna art. 6 ust. 1 lit. f RODO. Dodatkowe cookie marketingowe Facebook Pixel służą do mierzenia efektywności kampanii reklamowych, okres ważności 90 dni, kategoria marketingowe, podstawa prawna art. 6 ust. 1 lit. a RODO po wyrażeniu zgody. Cookie Google Ads służą do personalizacji reklam, okres ważności 60 dni, kategoria marketingowe, podstawa prawna art. 6 ust. 1 lit. a RODO po wyrażeniu zgody.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '5. Zarządzanie plikami cookie w przeglądarce', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Użytkownik ma pełną kontrolę nad plikami cookie przechowywanymi na jego urządzeniu. Większość przeglądarek internetowych domyślnie akceptuje pliki cookie, ale użytkownik może zmienić te ustawienia w dowolnym momencie. Możliwe jest zarówno całkowite zablokowanie automatycznego przyjmowania plików cookie, jak i informowanie o każdorazowym ich umieszczeniu na urządzeniu. Poniżej znajdują się instrukcje zarządzania cookie w najpopularniejszych przeglądarkach. W Google Chrome przejdź do Ustawienia Prywatność i bezpieczeństwo Pliki cookie i inne dane witryn. W Mozilla Firefox przejdź do Ustawienia Prywatność i ochrona Pliki cookie i dane witryn. W Safari przejdź do Preferencje Prywatność Zarządzaj danymi witryn. W Microsoft Edge przejdź do Ustawienia Pliki cookie i uprawnienia witryn. W każdej przeglądarce możesz wybrać między blokowaniem wszystkich cookie, blokowaniem cookie stron trzecich, blokowaniem cookie śledzących oraz akceptacją wszystkich cookie. Należy pamiętać, że zablokowanie cookie niezbędnych może spowodować utratę funkcjonalności strony w tym niemożność zalogowania się do Panelu B2B i zapisania preferencji językowych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '6. Narzędzia do blokowania reklam i trackerów', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Użytkownicy mogą dodatkowo zwiększyć poziom swojej prywatności za pomocą specjalnych rozszerzeń do przeglądarki, takich jak uBlock Origin, Privacy Badger, Ghostery czy DuckDuckGo Privacy Essentials. Rozszerzenia te blokują automatyczne śledzenie przez pliki cookie marketingowe oraz skrypty analityczne stron trzecich. Należy jednak pamiętać, że niektóre rozszerzenia mogą zakłócać działanie legitymnych funkcji strony, w tym odtwarzacza Radio HRL czy interfejsu platformy CMLP. Administrator nie ponosi odpowiedzialności za ograniczenia funkcjonalności spowodowane przez zewnętrzne narzędzia blokujące. W przypadku problemów z działaniem platformy po zainstalowaniu rozszerzeń, zalecamy wyłączenie filtrów dla domeny hardbanrecordslab.online oraz subdomeny cmlp.hardbanrecordslab.online.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '7. Pliki cookie stron trzecich', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Platforma HardbanRecords Lab może wykorzystywać usługi podmiotów trzecich, które same ustawiają pliki cookie na urządzeniu użytkownika. Dotyczy to przede wszystkim usług analitycznych Google Analytics, narzędzi marketingowych Google Ads, serwisów społecznościowych Facebook Pixel oraz systemu płatności Stripe. Każdy z tych podmiotów stosuje własne polityki ochrony prywatności i zarządzania cookie. Zachęcamy użytkowników do zapoznania się z politykami prywatności tych podmiotów, dostępnymi pod adresami policies.google.com, facebook.com/policy.php, stripe.com/pl/privacy. Administrator nie ma kontroli nad plikami cookie ustawianymi przez podmioty trzecie i nie ponosi za nie odpowiedzialności. Wszystkie podmioty trzecie, z którymi współpracuje HardbanRecords Lab, są zobowiązane do przestrzegania RODO oraz innych przepisów o ochronie danych osobowych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '8. Pliki cookie w kontekście RODO', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Zgodnie z wytycznymi Europejskiego Urzędu Ochrony Danych EDPB pliki cookie stanowią dane osobowe w rozumieniu RODO, ponieważ umożliwiają identyfikację użytkownika za pomocą unikalnego identyfikatora. Dlatego też administrator jest zobowiązany do świadczenia przejrzystych informacji o ich użyciu, pobierania świadomej zgody w przypadku cookie niepotrzebnych do świadczenia usługi oraz zapewnienia możliwości łatwej i swobodnej modyfikacji zgód w dowolnym momencie. Panele zgód cookie na platformie HRL zostały zaprojektowane zgodnie z wytycznymi EDPB i umożliwiają jednoczesną lub wybiórczą zgodę na różne kategorie plików cookie. Administrator regularnie audytuje rozwiązania techniczne w zakresie zarządzania cookie i dostosowuje je do zmian w przepisach oraz standardów branżowych. Prowadzimy również szkolenia z pracowników w zakresie ochrony danych osobowych i zarządzania cookie.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '9. Pliki cookie na urządzeniach mobilnych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Na urządzeniach mobilnych iOS, Android funkcjonalność plików cookie może być realizowana również za pomocą innych technologii, takich jak lokalne magazyny danych local storage, session storage, bazy danych IndexedDB oraz fingerprinting. Wszystkie te technologie podlegają tym samym regułom co pliki cookie i wymagają zgodnej zgody użytkownika w przypadku ich użycia do celów analitycznych lub marketingowych. System operacyjny iOS udostępnia dodatkowe funkcje ograniczające śledzenie między aplikacjami i stronami App Tracking Transparency, które użytkownik może włączyć w ustawieniach prywatności swojego urządzenia. Na platformie Android funkcje ograniczania śledzenia dostępne są od wersji systemu 13 wzwyż. Administrator rekomenduje włączenie tych funkcji w celu zwiększenia prywatności podczas korzystania z platformy HRL.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '10. Zmiany w polityce cookie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Zastrzegamy sobie prawo do wprowadzania zmian w niniejszej Polityce Cookies w dowolnym momencie. Zmiany mogą wynikać z aktualizacji technologii, nowych funkcji platformy, zmian w przepisach prawa lub dostosowania do wytycznych organów nadzorczych. O każdej zmianie poinformujemy użytkowników poprzez aktualizację daty powyżej oraz wyświetlenie powiadomienia o nowych cookies przy następnej wizycie na stronie. Zalecamy regularne zapoznawanie się z treścią niniejszej polityki w celu otrzymania aktualnych informacji na temat używanych plików cookie. W przypadku istotnych zmian dotyczących zakresu zbieranych danych lub celów przetwarzania, administrator wyśle dodatkowe powiadomienie na adres e-mail powiązany z kontem użytkownika.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '11. Kontakt w sprawie cookie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W przypadku pytań dotyczących użycia plików cookie na platformie HardbanRecords Lab prosimy o kontakt pod adresem e-mail contact@hardbanrecordslab.online lub telefonicznie pod numerem +48 726 651 384. Możesz również skorzystać z formularza kontaktowego dostępnego na stronie /contact/. Administrator udziela odpowiedzi na zapytania w ciągu 14 dni roboczych od dnia otrzymania zapytania. W przypadku pytań dotyczących zgód cookie, możesz zmienić preferencje w dowolnym momencie przez panel zgód dostępny w stopce strony lub przez ustawienia przeglądarki.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '12. Pozytywne zobowiązania administratora', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Administrator zobowiązuje się do przestrzegania zasady privacy by design oraz privacy by default przy projektowaniu nowych funkcji platformy. Wszystkie nowe funkcje, które mogą wymagać stosowania plików cookie lub podobnych technologii, będą poddawane ocenie wpływu na prywatność przed wdrożeniem. Administrator regularnie audytuje stosowane rozwiązania techniczne w zakresie zarządzania cookie i dostosowuje je do zmian w przepisach oraz standardów branżowych. Prowadzimy również szkolenia z pracowników w zakresie ochrony danych osobowych i zarządzania cookie. Wszystkie zobowiązania wynikające z niniejszej polityki są wdrożone w praktyce i podlegały okresowemu audytowi przez zewnętrznych ekspertów ds. ochrony danych.', 'hrl-theme' ); ?></p>
</div>
</div>
<?php get_footer(); ?>