<?php
/**
 * Template Name: Polityka Prywatności
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<div class="legal-page-wrapper">
<div class="legal-content">
    <h1><?php esc_html_e( 'Polityka Prywatności', 'hrl-theme' ); ?></h1>
    <p class="legal-date"><?php esc_html_e( 'Ostatnia aktualizacja: 12 lipca 2026 r.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '1. Administrator Danych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Administratorem Twoich danych osobowych jest HardbanRecords Lab, przedsiębiorstwo świadczące usługi w zakresie tworzenia, licencjonowania i dystrybucji oryginalnej muzyki komercyjnej oraz narzędzi cyfrowych wspierających branżę kreatywną, zarejestrowane w Polsce pod numerem NIP 1234567890, REGON 123456789 oraz wpisane do rejestru KRS pod numerem 0000123456. Siedziba i adres do korespondencji: HardbanRecords Lab, Polska. Dane kontaktowe w sprawach dotyczących ochrony danych osobowych: adres e-mail contact@hardbanrecordslab.online oraz numer telefonu +48 726 651 384. Administrator prowadzi działalność gospodarczą zgodnie z prawem polskim, rozporządzeniem RODO oraz innymi obowiązującymi regulacjami w zakresie ochrony danych osobowych. Powierzenie administratorowi danych osobowych oznacza wyrażenie zgody na ich przetwarzanie zgodnie z postanowieniami niniejszej polityki prywatności.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'W przypadkach, gdy przetwarzanie danych osobowych realizowane jest w ramach usług świadczonych przez podmioty trzecie, administrator działa jako podmiot powierający przetwarzanie danych. Administrator wybiera podmioty trzecie z należytą starannością, weryfikuje ich compliance w zakresie RODO i zobowiązuje ich umowami do przestrzegania standardów bezpieczeństwa danych minimalizacyjności oraz przejrzystości. Lista podmiotów przetwarzających dane w imieniu administratora dostępna jest w sekcji dotyczącej udostępniania danych niniejszej polityki.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '2. Jakie dane zbieramy', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab zbiera różne kategorie danych osobowych w zależności od formy korzystania z platformy oraz rodzaju świadczonych usług. W przypadku użytkowników rejestrujących konto w Panelu B2B: imię i nazwisko osoby kontaktowej, nazwa firmy, numer NIP, REGON, adres siedziby firmy, adres do faktur, adres e-mail służbowy, numer telefonu służbowego, stanowisko w firmie oraz dane uwierzytelniające do Panelu B2B (hasło, tokeny sesji, kod TOTP). W przypadku klientów korzystających z usług płatnych: dane do faktury, dane kart płatniczych przetwarzane wyłącznie przez bezpiecznego operatora płatności w imieniu administratora, historia transakcji, historia subskrypcji, preferencje dotyczące planów licencyjnych. W przypadku użytkowników Newslettera: imię, nazwisko, adres e-mail, preferencje dotyczące tematyki wiadomości podstawowych. W przypadku wszystkich użytkowników platformy: adres IP, informacje o urządzeniu end-user, systemie operacyjnym, przeglądarce internetowej, historię logowania do Panelu B2B, logi odtworzeń utworów, playlisty utworzonych przez użytkownika, preferencje muzyczne oraz dane statystyczne dotyczące korzystania z platformy. W przypadku osób kontaktujących się przez formularze kontaktowe: imię, nazwisko lub nazwa firmy, adres e-mail, temat zapytania, treść wiadomości oraz inne dane dobrowolnie podane przez użytkownika.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Administrator może zbierać dodatkowe dane osobowe jeśli użytkownik dobrowolnie wypełni formularz z danymi. Zebrane dane przetwarzane są zgodnie z RODO. Wszystkie dane zbierane są zgodnie z zasadą minimalizacji danych — administrator zbiera wyłącznie te dane, które są niezbędne do celu, dla którego są przetwarzane. W przypadku gdy dane nie są dłużej potrzebne do celów przetwarzania, administrator usuwa je lub anonimizuje zgodnie z polityką retencji danych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '3. Cel przetwarzania', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Dane osobowe przetwarzane przez HardbanRecords Lab są wykorzystywane w następujących celach i na następujących podstawach prawnych: realizacja umowy licencyjnej i świadczenie usług CMLP — podstawą prawną jest art. 6 ust. 1 lit. b RODO (wykonanie umowy). Obejmuje to zarządzanie kontem użytkownika, obsługę licencji, tworzenie playlist, analizę statystyczną odtworzeń, rozliczenia abonamentowe oraz wsparcie techniczne; obsługa płatności i rozliczeń finansowych — podstawą prawną jest art. 6 ust. 1 lit. b RODO (wykonanie umowy) oraz art. 6 ust. 1 lit. c RODO (obowiązek prawny). Obejmuje przetwarzanie transakcji, wystawianie faktur, rozliczenia podatkowe oraz archiwizację dokumentów księgowych zgodnie z ustawą o rachunkowości; wysyłka newslettera i komunikacja marketingowa — podstawą prawną jest art. 6 ust. 1 lit. a RODO (zgoda użytkownika). Obejmuje wysyłkę wiadomości e-mail z informacjami o nowych utworach, aktualizacjach platformy, raportach rynkowych oraz ofertach specjalnych. Zgoda może być wycofana w dowolnym momencie; analiza statystyczna i ulepszanie usług — podstawą prawną jest art. 6 ust. 1 lit. f RODO (prawnie uzasadniony interes administratora). Obejmuje anonimowe dane telemetryczne, logi dostępu, preferencje użytkowników oraz metryki wydajności platformy; zapobieganie oszustwom i zapewnienie bezpieczeństwa — podstawą prawną jest art. 6 ust. 1 lit. f RODO. Obejmuje weryfikację tożsamości, monitorowanie podejrzanych działań, blokowanie kont fałszywie zarejestrowanych; obowiązki podatkowe i księgowe — podstawą prawną jest art. 6 ust. 1 lit. c RODO (obowiązek prawny). Obejmuje dane niezbędne do wypełnienia obowiązków podatkowych i księgowych wynikających z przepisów ustawy o rachunkowości oraz ustawy o VAT.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '4. Pliki cookie', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Platforma HardbanRecords Lab korzysta z plików cookie oraz podobnych technologii w celu zapewnienia poprawnego funkcjonowania serwisu, dostosowania zawartości do preferencji użytkownika oraz analizy sposób korzystania z platformy. Wykorzystujemy następujące kategorie plików cookie: cookie sesyjne techniczne niezbędne do funkcjonowania platformy, w tym utrzymania sesji logowania do Panelu B2B, pamięci preferencji językowych oraz ustawień bezpieczeństwa; cookie preferencyjne umożliwiające zapisanie wyborów użytkownika dotyczących interfejsu platformy; cookie analityczne zbierające statystyki dotyczące ruchu na stronie w formie anonimowej, aktywowane wyłącznie po wyrażeniu zgody przez użytkownika; cookie marketingowe, wykorzystywane do personalizacji komunikacji i remarketingu, również wymagające wyraźnej zgody użytkownika przed ustawieniem. Użytkownik może w dowolnym momencie zmienić preferencje dotyczące cookie w ustawieniach przeglądarki lub za pomocą panelu zgód dostępnego na stronie. Szczegółowa informacja dotycząca rodzajów, celu oraz okresu ważności poszczególnych plików cookie dostępna jest w Polityce Cookies dostępnej pod adresem /cookies/.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '5. Twoje prawa RODO', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Jako osoba, której dane osobowe są przetwarzane przez HardbanRecords Lab, masz szereg praw wynikających z Rozporządzenia Parlamentu Europejskiego i Rady UE 2016/679 RODO. Masz prawo dostępu do swoich danych osobowych — możesz zażądać potwierdzenia, czy dane osobowe dotyczące ciebie są przetwarzane oraz uzyskać dostęp do ich treści. Masz prawo do sprostowania danych — możesz zażądać poprawienia nieprawidłowych danych oraz uzupełnienia niekompletnych. Masz prawo do usunięcia danych tzw. prawo do bycia zapomnianym — możesz zażądać usunięcia danych, jeśli nie są już niezbędne do celów, dla których były zbierane, lub jeśli wycofałeś zgodę na ich przetwarzanie. Masz prawo do ograniczenia przetwarzania — możesz zażądać ograniczenia przetwarzania w przypadkach wątpliwości co do prawidłowości danych, nieprawidłowości przetwarzania lub gdy dane są niezbędne do ustalenia, dochodzenia lub obrony roszczeń. Masz prawo do przenoszenia danych — możesz otrzymać swoje dane osobowe w formacie strukturyzowanym, powszechnie używanym i maszynowo czytelnym oraz przenieść je do innego administratora. Masz prawo do sprzeciwu — możesz wnieść sprzeciw wobec przetwarzania danych w celach marketingu bezpośredniego lub w celach naukowych, historycznych lub statystycznych. Masz prawo do wycofania zgody — jeśli przetwarzanie opiera się na zgodzie, możesz ją wycofać w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania dokonanego przed wycofaniem. Masz prawo wniesienia skargi do organu nadzorczego — każda osoba ma prawo wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych (PUODO) na adres: ul. Stawki 2, 00-193 Warszawa, jeśli uważa, że przetwarzanie danych osobowych narusza przepisy RODO.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '6. Okres przechowywania', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Dane osobowe są przechowywane przez okres nie dłuższy, niż jest to niezbędne do celów, dla których są przetwarzane. Okresy przechowywania dla poszczególnych kategorii danych: Dane identyfikacyjne i kontaktowe klientów B2B — przez okres obowiązywania umowy licencyjnej oraz 5 lat po jej zakończeniu, zgodnie z okresem przedawnienia roszczeń wynikających z przepisów ustawy o rachunkowości. Dane płatności i transakcje — przez okres obowiązywania umowy oraz 5 lat po jej zakończeniu, zgodnie z wymaganiami podatkowymi i regulacjami podmiotów płatniczych. Logi systemowe i telemetria — przez okres 12 miesięcy od zdarzenia, chyba że przepisy prawa wymagają dłuższego okresu. Zgody marketingowe — przez okres obowiązywania zgody, do momentu wycofania lub cofnięcia zgody przez administratora. Po upływie okresów przechowywania dane są trwale usuwane lub anonimizowane. W przypadku trwających postępowań prawnych lub administracyjnych, okres przechowywania danych może zostać przedłużony zgodnie z obowiązującymi przepisami.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '7. Udostępnianie danych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Dane osobowe użytkowników platformy HardbanRecords Lab nie są sprzedawane ani wynajmowane osobom trzecim. HardbanRecords Lab udostępnia dane osobowe wyłącznie następującym kategoriom odbiorców, którzy przetwarzają je wyłącznie w celu określonym przez administratora: podmioty obsługujące płatności elektroniczne (Stripe Payments Europe Limited, PayPal Pte. Ltd., PayU S.A.), podmioty świadczące usługi hostingowe i infrastrukturalne (DigitalOcean LLC, Hetzne Online GmbH, Amazon Web Services Inc.), podmioty świadczące usługi pocztowe i kurierskie do wysyłki faktur papierowych, podmioty świadczące usługi księgowe i audytowe, instytucje publiczne uprawnione do żądania danych na podstawie przepisów prawa, podmioty świadczące usługi wsparcia technicznego oraz inne podmioty, wobec których administrator ma obowiązek udostępnienia danych na podstawie obowiązujących przepisów prawa. Wszyscy podmioty przetwarzające dane osobowe w imieniu administratora zobowiązani są do przestrzegania RODO i innych przepisów o ochronie danych osobowych oraz podpisują umowy powierzenia przetwarzania danych przed rozpoczęciem współpracy.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '8. Bezpieczeństwo', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab stosuje odpowiednie środki techniczne i organizacyjne w celu zabezpieczenia danych osobowych użytkowników przed utratą, zniszczeniem, nieautoryzowanym dostępem, ujawnieniem lub modyfikacją. Środki bezpieczeństwa obejmują: szyfrowanie wszystkich transmisji danych za pomocą protokołu TLS 1.3 z certyfikatami SSL wydawanymi przez Let’s Encrypt, hashowanie haseł użytkowników za pomocą algorytmu bcrypt z losową solą, izolację środowisk produkcyjnych za pomocą kontenerów Docker z restrykcyjnymi regułami sieciowymi, regularne kopie zapasowe bazy danych przechowywane w bezpiecznych, geograficznie oddalonych lokalizacjach, monitorowanie dostępu do systemów za pomocą narzędzi Uptime Kuma oraz Sentry, uwierzytelnianie dwuskładnikowe dla wszystkich użytkowników Panelu B2B, restrykcyjne uprawnienia systemowe na serwerach produkcyjnych, sowie regularne audyty bezpieczeństwa przeprowadzane przez zewnętrznych ekspertów. W razie stwierdzenia naruszenia bezpieczeństwa danych osobowych, administrator niezwłocznie powiadomi odpowiedni organ nadzorczy oraz dotkniętych użytkowników zgodnie z obowiązującymi przepisami prawa.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '9. Dane nieletnich', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Usługi platformy HardbanRecords Lab są skierowane wyłącznie do osób pełnoletnich, czyli korzystających z pełnej zdolności do czynności prawnych zgodnie z prawem polskim. Platforma nie jest przeznaczona do świadczenia usług osobom nieletnim. Jeśli użytkownik ma ukończone 16 lat i korzysta z platformy bez express zgody rodzica lub opiekuna prawnego, zobowiązany jest do powiadomienia rodzica lub opiekuna o przetwarzaniu jego danych osobowych przez administratora. W przypadku uzyskania informacji o nieletnim użytkowniku, administrator podejmie działania niezwłoczne, w tym zablokowanie konta i usunięcie pobranych danych zgodnie z obowiązującym prawem. Rodzice lub opiekunowie prawni nieletnich użytkowników mają prawo do żądania dostępu do danych dziecka, ich sprostowania lub usunięcia, kontaktując się z administratorem pod adresem contact@hardbanrecordslab.online.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '10. Zmiany polityki', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Zastrzegamy sobie prawo do wprowadzania zmian w niniejszej Polityce Prywatności w dowolnym momencie z przyczyn uzasadnionych, w szczególności zmianami w przepisach prawa, rozwojem technologii, wprowadzaniem nowych funkcji platformy lub dostosowaniem polityki do wytycznych organów nadzorczych. O każdej zmianie polityki prywatności administrator poinformuje użytkowników co najmniej na 14 dni roboczych przed wejściem zmian w życie, poprzez opublikowanie nowej wersji na stronie internetowej oraz wysłanie powiadomienia na adres e-mail powiązany z kontem użytkownika. Kontynuowanie korzystania z platformy po wprowadzeniu zmian oznacza akceptację nowych postanowień polityki prywatności. Użytkownik, który nie zgadza się z nowymi postanowieniami, może w każdym momencie zrezygnować z korzystania z platformy i zażądać usunięcia swoich danych osobowych.', 'hrl-theme' ); ?></p>
    <p><?php esc_html_e( 'Wszelkie pytania, sugestie lub skargi dotyczące przetwarzania danych osobowych oraz niniejszej Polityki Prywatności można kierować do administratora na adres e-mail contact@hardbanrecordslab.online, telefonicznie pod numerem +48 726 651 384 lub pisemnie na adres siedziby HardbanRecords Lab. Administrator udziela odpowiedzi na zapytania i skargi w ciągu 14 dni roboczych od dnia otrzymania zapytania. W uzasadnionych przypadkach termin może zostać przedłużony o kolejne 14 dni, o czym administrator informuje użytkownika przed upływem pierwotnego terminu. Realizacja praw i odpłatność na zapytania jest bezpłatna.', 'hrl-theme' ); ?></p>
</div><!-- .legal-content -->
</div><!-- .legal-page-wrapper -->
<?php get_footer(); ?>