<?php
/**
 * Template Name: Regulamin Newslettera
 * @package HRL_Theme
 *Last updated: 2026-07-12
 */
get_header();
?>
<div class="legal-page-wrapper">
<div class="legal-content">
    <h1><?php esc_html_e( 'Regulamin Newslettera HRL Intel', 'hrl-theme' ); ?></h1>
    <p class="legal-date"><?php esc_html_e( 'Ostatnia aktualizacja: 12 lipca 2026 r.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '1. Postanowienia ogólne', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Niniejszy Regulamin Newslettera HRL Intel określa zasady subskrypcji, wysyłki i korzystania z newslettera oferowanego przez HardbanRecords Lab. Korzystanie z usługi newslettera zgodnie z Regulaminem oznacza akceptację wszystkich jego postanowień. HardbanRecords Lab zastrzega sobie prawo do wprowadzania zmian w Regulaminie. O zmianach poinformujemy subskrybentów na podany podczas zapisu adres e-mail. Newsletter HRL Intel jest bezpłatną usługą informacyjną skierowaną do przedsiębiorców, menedżerów, producentów muzycznych, decydentów w branży gastronomicznej i hotelarstwa oraz wszystkich zainteresowanych tematyką licencjonowania muzyki komercyjnej, sztucznej inteligencji w kreatywnictwie i analiz rynkowych. Usługa nie stanowi oferty handlowej w rozumieniu Kodeksu Cywilnego, a jej treści mają wyłącznie charakter informacyjny i edukacyjny. Newsletter nie stanowi porady prawnej, finansowej ani biznesowej. Wszelkie decyzje biznesowe podejmowane na podstawie treści newslettera są podejmowane na własną odpowiedzialność subskrybenta.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '2. Warunki subskrypcji', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Subskrypcja newslettera jest możliwa dla każdej osoby fizycznej lub prawnej posiadającej ważny adres e-mail. Podczas zapisu wymagane jest podanie imienia i nazwiska oraz adresu e-mail. Dane te są przetwarzane wyłącznie w celach związanych z wysyłką newslettera. Subskrybent zobowiązany jest do podawania prawdziwych danych oraz ich aktualizacji w przypadku zmian. HardbanRecords Lab nie ponosi odpowiedzialności za nieprawidłowe działanie usługi newslettera spowodowane podaniem nieprawdziwych danych przez subskrybenta, w szczególności nieprawidłowego adresu e-mail. Subskrypcja jest bezpłatna i nie wiąże się z żadnymi obowiązkami finansowymi. Administrator zastrzega sobie prawo do wprowadzenia płatnej subskrypcji premium w przyszłości, o czym subskrybenci zostaną poinformowani z 30-dniowym wyprzedzeniem. W przypadku płatnej subskrypcji premium, subskrybenci otrzymają dodatkowe treści wyłączne, dostęp do archiwum newsletterów oraz priorytetowe zaproszenia na wydarzenia branżowe.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '3. Częstotliwość i zakres treści', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Newsletter HRL Intel jest wysyłany co najmniej raz w tygodniu, zwykle w piątek rano w godzinach 8:00-10:00 czasu polskiego. W przypadku istotnych wydarzeń rynkowych lub ważnych informacji dotyczących platformy CMLP, Administrator zastrzega sobie prawo do wysłania dodatkowego newslettera między stałymi nadawaniami. Każdy newsletter zawiera: analizę rynku muzyki komercyjnej i technologii audio, raporty specjalne dotyczące regulacji prawnych w branży muzycznej i licencjonowania, przewodniki praktyczne dla właścicieli lokali gastronomicznych i hotelarstwa, informacje o nowych utworach dodanych do katalogu CMLP, aktualizacje dotyczące platformy CMLP, nowych funkcji i integracji, zaproszenia na webinary, szkolenia i wydarzenia branżowe organizowane przez HardbanRecords Lab oraz partnerów, specjalne oferty i promocje dostępne wyłącznie dla subskrybentów newslettera, wywiady z ekspertami branży muzycznej i technologii, case studies klientów wykorzystujących platformę CMLP w swoich lokalach oraz porady praktyczne dotyczące wyboru muzyki dla różnych branż i profilów lokali.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '4. Zarządzanie subskrypcją', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Subskrybent może w dowolnym momencie zrezygnować z subskrypcji newslettera na dwa sposoby: klikając link Wypisz się znajdujący się na dole każdej wiadomości newslettera, lub wysyłając wiadomość e-mail na adres info@hardbanrecordslab.online z wyraźnym żądaniem wypisania z listy dystrybucyjnej oraz podaniem adresu e-mail, z którego wysłano wiadomość. Wypisanie z newslettera następuje w ciągu 48 godzin od otrzymania żądania i nie wymaga podania przyczyny. Administrator zatrzymuje wszystkie dane subskrybenta w ciągu 30 dni od wypisania, z wyjątkiem danych wymaganych przepisami podatkowymi i księgowymi, które przechowuje przez okres 5 lat. Wycofanie zgody na newsletter nie wpływa na zgodność z prawem przetwarzania danych dokonanego przed wycofaniem. Subskrybent może również zaktualizować swoje dane kontaktowe lub preferencje dotyczące treści newslettera, kontaktując się z administratorem pod adresem contact@hardbanrecordslab.online.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '5. Prawo do sprzeciwu i marketing', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Zgodnie z art. 21 RODO, subskrybent ma prawo w dowolnym momencie wnieść sprzeciw wobec przetwarzania jego danych osobowych w celach marketingu bezpośredniego, w tym tworzenia profili użytkownika. Sprzeciw powinien zostać złożony na piśmie, wysłany na adres contact@hardbanrecordslab.online, z wyraźnym zaznaczeniem, że dotyczy sprzeciwu wobec marketingu bezpośredniego. Administrator zatrzymuje przesyłanie komunikacji marketingowej do subskrybenta w ciągu 72 godzin od otrzymania sprzeciwu. Sprzeciw nie wpływa na zgodność z prawem przetwarzania danych dokonanego przed wniesieniem sprzeciwu. W przypadku gdy subskrybent skorzystał z prawa do sprzeciwu, jego dane nie będą już wykorzystywane do celów marketingowych, ale mogą być nadal przetwarzane w celach związanych z wykonywaniem umów lub obowiązków prawnych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '6. Bezpieczeństwo i poufność', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab stosuje odpowiednie środki techniczne i organizacyjne w celu zabezpieczenia danych osobowych subskrybentów przed utratą, zniszczeniem, nieautoryzowanym dostępem, ujawnieniem lub modyfikacją. Dane przechowywane są na serwerach z certyfikatem SSL/TLS, z regularnymi kopiami zapasowymi i systemami monitorowania. Dostęp do danych osobowych mają wyłącznie upoważnione osoby, podlegające obowiązkowi zachowania poufności. W razie stwierdzenia naruszenia bezpieczeństwa danych osobowych, Administrator niezwłocznie powiadomi odpowiedni organ nadzorczy oraz subskrybentów, jeśli naruszenie może spowodować wysokie ryzyko dla ich praw i wolności. Wszystkie dane subskrybentów są szyfrowane w spoczynku i w tranzycie.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '7. Wykorzystanie danych osobowych', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Dane osobowe subskrybentów newslettera przetwarzane są wyłącznie w celach związanych z wysyłką newslettera, w tym: dostosowania treści newslettera do preferencji subskrybenta, analizy statystycznej dotyczącej otwierania wiadomości i klikania w linki, segmentacji listy dystrybucyjnej w celach marketingowych, rozsyłania informacji o nowych produktach i usługach HardbanRecords Lab, rozsyłania zaproszeń na wydarzenia branżowe, webinary i szkolenia, rozsyłania specjalnych ofert i promocji dostępnych wyłącznie dla subskrybentów newslettera, realizacji obowiązków prawnych wynikających z przepisów o ochronie danych osobowych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '8. Kontakt w sprawach newslettera', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W sprawach dotyczących newslettera, subskrypcji, wypisania z listy dystrybucyjnej lub aktualizacji danych kontaktowych, prosimy o kontakt pod adresem e-mail contact@hardbanrecordslab.online lub info@hardbanrecordslab.online. Administrator udziela odpowiedzi w ciągu 14 dni roboczych od dnia otrzymania zapytania. W przypadku pytań dotyczących treści newslettera, prosimy o odpowiedzenie bezpośrednio na wiadomość newslettera, aby nasz zespół mógł Ci odpowiedzieć w jak najkrótszym czasie.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '9. Odpowiedzialność za treści', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab dokłada wszelkich starań, aby treści newslettera były aktualne, wiarygodne i wartościowe dla subskrybentów. Administrator nie ponosi jednak odpowiedzialności za ewentualne błędy, nieścisłości lub przestarzałe informacje zawarte w newsletterze, a także za szkody wynikające z wykorzystania treści newslettera do celów biznesowych lub inwestycyjnych. Treści newslettera mają charakter wyłącznie informacyjny i nie stanowią porady prawnej, finansowej ani biznesowej. Subskrybenci powinni konsultować wszystkie decyzje biznesowe i inwestycyjne z wykwalifikowanymi specjalistami.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '10. Zmiany regulaminu', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Zastrzegamy sobie prawo do wprowadzania zmian w niniejszym Regulaminie Newslettera w dowolnym momencie z przyczyn uzasadnionych, w szczególności zmianami w przepisach prawa, rozwojem technologii, wprowadzaniem nowych funkcji platformy lub dostosowaniem regulaminu do wytycznych organów nadzorczych. O każdej zmianie regulaminu administrator poinformuje subskrybentów co najmniej na 14 dni roboczych przed wejściem zmian w życie, poprzez opublikowanie nowej wersji regulaminu na stronie internetowej oraz wysłanie powiadomienia na adres e-mail powiązany z subskrypcją. Kontynuowanie korzystania z newslettera po wprowadzeniu zmian oznacza akceptację nowych postanowień regulaminu.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '11. Bezpieczeństwo systemu newslettera', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Platforma newslettera HRL Intel opiera się na zaufanej infrastrukturze przesyłania wiadomości e-mail z certyfikatem SSL/TLS, z regularnymi kopiami zapasowymi listy dystrybucyjnej i systemami monitorowania dostarczalności wiadomości. HardbanRecords Lab stosuje środki przeciw spamowym, w tym autoryzację DKIM, SPF i DMARC dla domeny hardbanrecordslab.online, co gwarantje wysoką dostarczalność wiadomości i chroni przed fałszywymi wiadomościami phishingowymi. W przypadku problemów z dostarczaniem newslettera do skrzynki e-mail, prosimy o sprawdzenie folderu spamowego i dodanie adresu info@hardbanrecordslab.online do listy kontaktów bezpiecznych.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '12. Archiwum newsletterów i historia', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Wszystkie wiadomości newslettera HRL Intel archiwizowane są na platformie HardbanRecords Lab przez okres 24 miesięcy od daty wysłania. Subskrybenci mogą w dowolnym momencie przeglądać archiwum newsletterów dostępne pod adresem /newsletter/archiwum/ po zalogowaniu się do Panelu B2B lub pod adresem e-mail powiązanym z subskrypcją. W przypadku płatnej subskrypcji premium, subskrybenci otrzymują dostęp do pełnego archiwum newsletterów bez ograniczeń czasowych, co pozwala na przeglądanie wszystkich historii treści edukacyjnych i analiz rynkowych publikowanych od początku działalności platformy.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '13. Wykorzystanie treści newslettera', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'Treści publikowane w newsletterze HRL Intel, w tym artykuły, analizy, raporty i wywiady, są własnością intelektualną HardbanRecords Lab i chronione są przepisami o prawie autorskim. Subskrybenci nie mają prawa do kopiowania, powielania, dystrybucji ani publikacji treści newslettera bez wyraźnej pisemnej zgody administratora. Zezwala się na krótkie cytaty do celów niekomercyjnych pod warunkiem wskazania źródła i autora. W przypadku chęci wykorzystania treści newslettera do celów komercyjnych lub publikacji w mediach, prosimy o kontakt z administratorem w celu uzyskania odpowiedniej licencji lub zgody. HardbanRecords Lab zastrzega sobie prawo do dochodzenia odszkodowań w przypadku naruszenia praw autorskich.', 'hrl-theme' ); ?></p>

    <h2><?php esc_html_e( '14. Dostępność usługi newslettera', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'HardbanRecords Lab dokłada wszelkich starań, aby usługa newslettera była dostępna w sposób ciągły i niezawodny. Jednak administrator nie gwarantuje nieprzerwanej dostępności usługi i zastrzega sobie prawo do czasowego przerwania wysyłki newslettera z przyczyn uzasadnionych, w tym awarii infrastruktury, planowanych prac konserwacyjnych lub działania siły wyższej. W przypadku przerwania wysyłki newslettera, administrator poinformuje subskrybentów o przyczynie i przewidywanym czasie przywrócenia usługi. W przypadku trwałego zaprzestania świadczenia usługi newslettera, administrator poinformuje subskrybentów z 30-dniowym wyprzedzeniem i zaoferuje możliwość pobrania archiwum newsletterów lub zapisu do nowej usługi informacyjnej.', 'hrl-theme' ); ?></p>    <h2><?php esc_html_e( '15. Reklamacje i sporów', 'hrl-theme' ); ?></h2>
    <p><?php esc_html_e( 'W przypadku reklamacji dotyczących treści newslettera, częstotliwości wysyłki, problemów z zapisaniem się lub wypisaniem z listy dystrybucyjnej, Subskrybent zobowiązany jest do złożenia reklamacji w formie pisemnej na adres e-mail contact@hardbanrecordslab.online z wyraźnym zaznaczeniem tematu Reklamacja newsletter. Reklamacja powinna zawierać pełne dane subskrybenta, adres e-mail powiązany z subskrypcją, opis problemu oraz proponowany sposób rozwiązania. Administrator rozpatrzy reklamację w ciągu 14 dni roboczych od dnia otrzymania i powiadomi subskrybenta o wyniku postępowania. W przypadku uzasadnionej reklamacji, administrator podejmie odpowiednie działania naprawcze, w tym poprawienie błędu w systemie, ponowne wysłanie newslettera lub innego rozwiązania zgodnego z przyczynami reklamacji. W przypadku sporów między subskrybentem a administratorem, strony zobowiązują się do rozstrzygnięcia sporu na drodze mediacji przed skierowaniem sprawy do sądu.', 'hrl-theme' ); ?></p>    <p><?php esc_html_e( 'Dziękujemy za subskrypcję newslettera HRL Intel. Jesteśmy do dyspozycji i pomożemy Ci w każdej kwestii dotyczącej subskrypcji, treści newslettera lub współpracy z HardbanRecords Lab. Skontaktuj się z nami pod adresem contact@hardbanrecordslab.online lub +48 726 651 384.', 'hrl-theme' ); ?></p>


</div>
</div>
<?php get_footer(); ?>